### PR TITLE
support options where with __unlink__

### PR DESCRIPTION
**Pull request by sqlwwx**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
Hello @sqlwwx, thank you for your patch. If I understand it correctly, you are proposing this new API (assuming `Product hasAndBelongsToMany Category`):

```js
Product.categories.remove({ where: /* query */ });
```

I have two concerns:

 1. It is not (easily) possible to expose this new `where` option via the REST API.
 2. None of the other data-access operation use `options` to modify the result of the operation so far. If an operation accepts a query, then this is typically a new argument.

In that light, I am proposing to modify your implementation as follows:

```js
HasManyThrough.prototype.remove = function(acInst, where, options, cb) {
   // relation.remove(acInst, options, cb)
   // "options" take precedence over "where" for backwards compatibility
   if (typeof options === 'function' && cb === undefined) {
     cb = options;		     
     options = where;
     where = {};
   }

   // relation.remove(acInst, cb)
   if (typeof where === 'function' && options === undefined && cb === undefined) {
     cb = where;
     options = {};
   }

   // continue with your current code
}
```

We also need you to add new unit-tests to cover this new feature and prevent regressions in the future.

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
@sqlwwx Last but not least, please rebase your patch on the latest master:

```
git fetch strongloop
git rebase strongloop/master
git push -f
```

**Comment by bajtos** [comment]
I am closing this pull request as abandoned. @sqlwwx feel free to reopen this pull request if/when you get time to work on it again in the future.

**Pull request closed without merging**
