### PR TITLE
Update helper scripts

### PR DESCRIPTION
**Pull request by superkhau**
Cleaned up the Makefile and added a few helper scripts.

### CODE REVIEW

**Comment by superkhau** [comment]
@slnode test please

**Comment by superkhau** [comment]
@raymondfeng Code review please. I want to merge this, but I think there are issues with CI.

**Comment by superkhau** [comment]
@rmg Any reason why the above is failing? I'm only changing a makefile.

**Comment by raymondfeng** [comment]
LGTM even though I don't see high value to have the extra helper targets.

**Comment by superkhau** [comment]
@raymondfeng Its only to speed up simple repetitive tasks during dev time. I also don't want to accidently rm -rf the wrong dir on my system. ;p

**Pull request merged**
