### PR TITLE
Custom Table Names on hasAndBelongsToMany Relationships

### PR DESCRIPTION
**Pull request by waldemarzahn**
### Description
Custom Table Names on hasAndBelongsToMany Relationships

#### Related issues
- #230 Custom Table Names on hasAndBelongsToMany Relationships

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ssh24** [comment]
@slnode ok to test

**Comment by ssh24** [comment]
Not sure why CI is saying PR needs to be rebased even after I rebased it. Same for fixing the commit linter.

**Comment by kjdelisle** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@waldemarzahn Thank you for the contribution! PR is ready to be landed.

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by bdharrington7** [comment]
Somewhat related: is there a way to specify the column names for the join table? I get this error:

```
{
  "error": {
    "statusCode": 500,
    "name": "error",
    "message": "column \"thingid\" does not exist",
    "length": 166,
    "severity": "ERROR",
    "code": "42703",
    "hint": "Perhaps you meant to reference the column \"links.thing_id\".",
    "position": "13",
    "file": "parse_relation.c",
    "line": "3183",
    "routine": "errorMissingColumn",
    "stack": "error: column \"thingid\" does not exist\n    at Connection.parseE (/Users/brian/bbs/dri/node_modules/pg/lib/connection.js:569:11)\n    at Connection.parseMessage (/Users/brian/bbs/dri/node_modules/pg/lib/connection.js:396:17)\n    at Socket.<anonymous> (/Users/brian/bbs/dri/node_modules/pg/lib/connection.js:132:22)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at Socket.Readable.push (_stream_readable.js:134:10)\n    at TCP.onread (net.js:548:20)"
  }
}
```

as you can see from the error, I have a column name in the join table called `thing_id` where loopback is expecting `thingid` (and the other join column `otherthing_id` will have the same issue, I presume)

I tried setting primary and foreign keys but it didn't seem to work:

```
"relations": {
    "modules": {
      "type": "hasAndBelongsToMany",
      "model": "Module",
      "throughTable": "links",
      "foreignKey": "otherthing_id",
      "primaryKey": "thing_id"
    }
```

**Comment by TristanMarion** [comment]
This is not in the `HasAndBelongsToMany` relations documentation (https://loopback.io/doc/en/lb2/HasAndBelongsToMany-relations.html), it would be nice to have it.
Thanks !

**Pull request merged**
