### PR TITLE
fix: alllow updates with unknown properties if strict=filter

### PR DESCRIPTION
**Pull request by mrfelton**
Fix for #1422 

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

---

Update:

It should also fix issue https://github.com/strongloop/loopback-connector-mongodb/issues/445

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ssh24** [comment]
@mrfelton Thank you for the patch. Could you please add some test coverage to avoid future regressions?

Also please fix the commit message, the first line of the commit message should be less than 50 characters long.

**Comment by mrfelton** [comment]
@ssh24 I've updated the PR to add a test case as well as fixing the format of the commit message. Can you give another check please? Thanks

**Comment by mrfelton** [comment]
Would be great if we could get this in sometime soon before the bot closes the issue due to inactivity!

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by drtobal** [comment]
Hi.
Any date or release to implement this?
Regards.

**Comment by Elrendio** [comment]
This issue should not be closed.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
Sorry for closing it as a stale PR. I reopened and rebased it. Triggered a new build.

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jamesjjk** [comment]
@raymondfeng @jannyHou This still remains an issue to date for the latest version of loopback: 3.35.0 an update would be appreciated as this could cause security issues for many projects.

**Comment by theBull** [comment]
This appears to still be an issue in version ^4.26.0 (according to `node_modules/@loopback/repository/package.json`).

**Pull request merged**
