### PR TITLE
Using a filter with exclusion of a non existent property, removes an existing one

### PR DESCRIPTION
**Pull request by mitsos1os**
### Description
Fixes the referrenced issue for excluding non existing fields

#### Related issues

#1256 

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ssh24** [comment]
@slnode ok to test

**Comment by ssh24** [comment]
Hey, @mitsos1os. Thanks for the contribution. Your test case is failing for mongodb: 
```
1) mongodb imported features basic-querying find should ignore non existing properties when excluding:
     Uncaught AssertionError: expected Array [ 'seq', 'name', 'order', 'vip', 'id' ] to contain Array [
  'id',
  'seq',
  'name',
  'email',
  'role',
  'order',
  'birthday',
  'vip',
  'address',
  'friends'
]
      at Assertion.fail (node_modules/should/lib/assertion.js:92:17)
      at Assertion.Object.defineProperty.value [as containDeep] (node_modules/should/lib/assertion.js:164:19)
      at node_modules/loopback-datasource-juggler/test/basic-querying.test.js:606:43
      at Array.forEach (native)
      at node_modules/loopback-datasource-juggler/test/basic-querying.test.js:605:15
      at node_modules/loopback-datasource-juggler/lib/dao.js:2048:9
      at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1012:9
      at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:359:16
      at iteratorCallback (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:935:13)
      at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:843:16
      at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:1009:13
      at buildResult (node_modules/loopback-datasource-juggler/lib/dao.js:2014:11)
      at node_modules/loopback-datasource-juggler/lib/dao.js:2028:13
      at node_modules/loopback-datasource-juggler/lib/observer.js:112:23
      at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:359:16
      at replenish (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:876:25)
      at iterateeCallback (node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:866:17)
      at node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:843:16
```
Could you please take a look? To test it against mongodb, git clone the `loopback-connector-mongodb` and npm link your datasource-juggler with the mongodb clone and run `npm test`.

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@mitsos1os Could you please rebase your branch? If you do not how to, you could also give me access to your fork so I can rebase it for you. More info: https://github.com/blog/2247-improving-collaboration-with-forks

**Comment by mitsos1os** [comment]
@ssh24 I have enabled edits from mainteners option. If you want you can do it now because I am away from a laptop right now. Alternatively I can rebase it myself tomorrow when I get back to office. Whatever suits you best. 
Thanks

**Comment by ssh24** [comment]
@mitsos1os I was looking through your master branch and it looks like you have commits in there for some reason https://github.com/mitsos1os/loopback-datasource-juggler/commits/master. Please revert those commits as it will give bunch of merge conflicts when rebasing against your master.

**Comment by mitsos1os** [comment]
@ssh24 Nevermind! My master was behind I used a local branch to rebase! I rebased it myself! It should be ok now!

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode ok to test

**Pull request merged**
