### PR TITLE
Fixing the query where in the related models

### PR DESCRIPTION
**Pull request by f0rmiga**
### Description

Fixed querying with where in the related models.

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by f0rmiga** [comment]
@jannyHou I created another pull request... I did a complete mess in the other pull request... sorry about that. I just reapplied the changes I made. Please just double check the tests. Thanks.

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@f0rmiga no worries let's continue in this PR, sorry I am busy with something today but will review it right after finishing some urgent task.

**Comment by joostdebruijn** [comment]
Will this PR land anytime soon? I would like to use this functionality.

**Comment by kjdelisle** [comment]
@slnode test please

**Comment by f0rmiga** [comment]
@kjdelisle No problem. I gave permission to the strongloop team to rebase. You can do it at your will, or when it makes more sense.

**Comment by jannyHou** [comment]
@kjdelisle Sorry I have been busy with both personal emergency and the LBnext story, this PR fails due to https://github.com/strongloop-internal/scrum-apex/issues/298, I need time to investigate why function [`smartMerge`](https://github.com/strongloop/loopback-datasource-juggler/pull/1480/files#diff-c2a679b29102d5574291e884531cb8aeL119) has bug.

**Comment by jannyHou** [comment]
Working on the fix and will get back to you soon when CI passes.

**Comment by f0rmiga** [comment]
Thank you @jannyHou.

**Comment by jannyHou** [comment]
@f0rmiga looks like you somehow revert the rebase :-p I just rebased your PR 30 mins ago, so don't worry about the rebase thing.

**Comment by jannyHou** [comment]
It's a little hard to coordinate the work if we modify the same branch at same time, I will create a new branch in strongloop/juggler and copy paste your code + my fix and get CI pass first (but I WONT merge it, just for testing), then I can give you my working code then continue our chat in this PR.

BTW, merge from your forked master branch would cause potential problem since everytime you commit to your master directly, it could not sync with remote master anymore, so I would suggest keep create a new branch in your forked repo and merge from there, then you can keep your master sync with the remote master easily :)

**Comment by f0rmiga** [comment]
@jannyHou thanks for the advice.

**Comment by jannyHou** [comment]
I believe the related query will be fixed by code in PR https://github.com/strongloop/loopback-datasource-juggler/pull/1491

But now it fails due to another validation problem. I don't have bandwidth to dig into it this week, will continue fixing it next week.

**Comment by jannyHou** [comment]
Hi @f0rmiga I updated some fix based on your PR, I believe the code in https://github.com/strongloop/loopback-datasource-juggler/pull/1491 should fix all problem raised by related query. Feel free to use or modify it here then I can help you check in this one.

There are some CI failures now but not because your change. I need to fix them first then check in yours.

**Comment by joostdebruijn** [comment]
Are there any updates on this one?

**Comment by jannyHou** [comment]
hi @f0rmiga I added more fix based on your PR to get CI pass, please see code in https://github.com/strongloop/loopback-datasource-juggler/pull/1491/files

Could you create a new branch in your forked repository for your fix + my fix? So the bonus still goes to you :) 

This PR is created from forked master branch, therefore I could not rebase it....

**Comment by joostdebruijn** [comment]
I know it may be seen as impolite and maybe I am too rushed, but with the best intentions I just created PR #1522 with a merge of all the changes made to make this functionality work. I apologize if that is undesirable!

**Comment by kjdelisle** [comment]
@joostdebruijn I'm okay with that. I'll close this one instead. Let me know if there's a reason to keep this one open and I'll reopen it.

**Comment by f0rmiga** [comment]
I'm fine with that. I think all people involved in this pull request are busy. That generated too much hassle to get this merged.

**Pull request closed without merging**
