### PR TITLE
User Provided Default Model Value Callbacks

### PR DESCRIPTION
**Pull request by tatemz**
### Description
In order to use custom defined `defaultFn` I added the following code to a `server/boot/manipulation.js` file to test this feature:

```
module.exports = function(server) {
  server.dataSources.mysql.defineDefaultFn(function MyDefaultName(prop, data) {
    return "John Doe"
  }, ['my-default-name']);
};
```

And my `model.json`:
```
{
  "name": "Human",
  "plural": "humans",
  "base": "PersistedModel",
  "idInjection": false,
  "options": {
  },
  "properties": {
    "name": {
      "type": "String",
      "required": true,
      "defaultFn": "MyDefaultName"
    },
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}

```

#### Related issues
- #458
- strongloop/loopback#292

### Checklist

- [ ] Add test to `manipulation.test.js` to register and handle custom `defaultFn`
- [ ] Community testing & feedback
- [ ] Review and approve how to define custom callbacks
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)
- [x] Sign Contributor License Agreement (CLA)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by raymondfeng** [comment]
@tatemz Thank you for the patch. I like the idea to allow custom functions to be registered and referenced in model definitions.

I'm not sure if `DataSource` is the best holder of such functions though. What about adding the capability to `app`? Please note each model can access the app via `MyModel.app`.

**Comment by bajtos** [comment]
@tatemz cool, thank you for the pull request!

I agree with @raymondfeng that datasource is not the best place where to keep a registry of default value factories.

> Please note each model can access the app via `MyModel.app`.

This is true for LoopBack models, but does not hold for loopback-datasource-juggler. 

In juggler, we are using `modelRegistry` as the object holding various lookup tables: not only models, but also types (see [lib/types.js](https://github.com/strongloop/loopback-datasource-juggler/blob/5a7283386c7dbda1b73ab07690a3e91b08867417/lib/types.js) and [initialization in model-builder](https://github.com/strongloop/loopback-datasource-juggler/blob/5a7283386c7dbda1b73ab07690a3e91b08867417/lib/model-builder.js#L24)).

I think we should use the same design for the registry of `defaultFn` functions:

 - In juggler, `ModelBuilder` keeps this registry, e.g. as `this.defaultFunctions`.
 - In LoopBack, it is the [registry](https://github.com/strongloop/loopback/blob/d2e9e7ee77c0ec64e0aa69c8aa8c286e1db714ce/lib/registry.js#L26) which hold the single `ModelBuilder` instance used across all models and datasource of the app. We should add a new API for registering custom `defaultFn` functions there too.

**Comment by bajtos** [comment]
@tatemz we will also need you to sign our Contributor License Agreement (CLA) - see one of the failed checks. Here is the link for your convenience: https://cla.strongloop.com/agreements/strongloop/loopback-datasource-juggler

**Comment by tatemz** [comment]
I agree that DataSource is probably not the best spot. I originally tried to apply it within `model.js` but had some roadblocks. I will try again and document what roadblocks those were to get you guys more details on how we can best structure this feature.

Another note is that this feature should probably be structured in such a way to handle custom callbacks that involve returning promises. :-/

**Comment by bajtos** [comment]
> Another note is that this feature should probably be structured in such a way to handle custom callbacks that involve returning promises. :-/

I am afraid that will be difficult if possible at all. Default values are created and assigned when a new model instance is created via JavaScript constructor call (`new MyModel()`), which is always strictly synchronous.

If you need asynchronous computation of default values, then I think you should use a different mechanism, for example you can use a `before save` or `persist` hook to fill in any missing values.

**Comment by bajtos** [comment]
@tatemz ping, what's the status of this pull request?

**Comment by bajtos** [comment]
Closing as abandoned. Feel free to reopen if/when you get time to work on this patch again.

**Pull request closed without merging**
