### PR TITLE
translation return for Q4 drop1

### PR DESCRIPTION
**Pull request by candytangnb**
translation return for Q4 drop1

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by dhmlau** [comment]
@candytangnb , could you please sign the CLA https://cla.strongloop.com/agreements/strongloop/loopback-datasource-juggler?  Thanks.

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode  test please

**Comment by dhmlau** [comment]
Currently CI is failing, it was failing before this PR.  @jannyHou has a PR for testing/fixing the CI failure in juggler. https://github.com/strongloop/loopback-datasource-juggler/pull/1498

When this PR has been reviewed, I'd like to force merge it because I don't think the CI failure is related to this change.  Thanks.

**Pull request merged**
