### PR TITLE
Add TTL for KeyValue related features

### PR DESCRIPTION
**Pull request by superkhau**
Backport of strongloop/loopback-datasource-juggler#1030

/cc @bajtos

### CODE REVIEW

**Comment by superkhau** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by superkhau** [comment]
Connect to strongloop-internal/scrum-loopback#954

**Comment by superkhau** [comment]
More reliable CI list at https://cis-jenkins.swg-devops.com/job/npr/job/loopback-datasource-juggler~2.x/45/

**Comment by rmg** [comment]
Looks like some of the commit statuses didn't get updated. Those `cis-jenkins` downstreams are all done. The `[cis-jenkins] downstream ...` statuses currently marked as failures are the only failures, and they appear to be unrelated.

**Pull request merged**
