### PR TITLE
Enable "between" filter for memory db connector

### PR DESCRIPTION
**Pull request by dbarbeau**
Hello,

I happen to be using the memory datasource a lot but couldn't get "between" requests to work as documented here:
http://docs.strongloop.com/display/public/LB/Where+filter#Wherefilter-between

After trying every combination I could think of I finally figured that it could be a bug on loopback's side.
So here is my modest contribution.

Daniel

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by raymondfeng** [comment]
@dbarbeau Thank you for the patch. Would you please add a test case?

**Comment by dbarbeau** [comment]
@raymondfeng : There's my attempt at adding test cases. Hope that's the way to do it ;)

**Comment by raymondfeng** [comment]
ok to test

**Comment by bajtos** [comment]
@dbarbeau we should have asked before landing this patch, but could you please sign our CLA? https://cla.strongloop.com/agreements/strongloop/loopback-datasource-juggler

**Comment by dbarbeau** [comment]
Did it work? I get this message "You'll need to sign into GitHub. Maybe next time?" although I am signed in, and the cla application is registered.

**Comment by bajtos** [comment]
> > @bajtos we should have asked before landing this patch, but could you please sign our CLA? https://cla.strongloop.com/agreements/strongloop/loopback-datasource-juggler

> @dbarbeau Did it work? I get this message "You'll need to sign into GitHub. Maybe next time?" although I am signed in, and the cla application is registered.

I don't think so, I don't see you in the list. @rmg could you PTAL?

**Comment by rmg** [comment]
I believe I've sorted out the CLA auth issue now. @dbarbeau can you try again?

**Comment by dbarbeau** [comment]
Hum, nope, it still returns the same "Maybe next time?" message.

**Comment by dbarbeau** [comment]
Ok now it worked :)

**Pull request merged**
