### PR TITLE
refactor: rename internal instance errors property to __errors

### PR DESCRIPTION
**Pull request by joseandrespg**
### Description

This fix ensures that you can define a property called `errors` inside your loopback model and it won't be overwritten by the internal validation.

#### Related issues

To fix this issue: https://github.com/strongloop/loopback-datasource-juggler/issues/1353

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ssh24** [comment]
@joseandrespg Thank you for the contribution. Could you please fix your commit message? The rules for the commit message is as follows:
```
1. The first line of the commit message should be less than 50 characters.
2. The second line should be allows left empty.
3. Every line after the second line should be less than 72 characters long.
```

**Comment by joseandrespg** [comment]
@ssh24 done. I tried to find the commit message guidelines, but I didn't find them. Probably would be a good idea to have them on the CONTRIBUTING document.

**Comment by ssh24** [comment]
@slnode ok to test

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@joseandrespg I rebased the branch for you. Please pull to get the latest.

CI is acting weird and failing on random downstream connectors. Need to look into that.

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@joseandrespg, could you also please sign the CLA https://cla.strongloop.com/agreements/strongloop/loopback-datasource-juggler?  Thanks.

**Comment by joseandrespg** [comment]
Hi @dhmlau, signed :+1:

**Comment by loay** [comment]
@joseandrespg Please rebase and ping either myself or @ssh24 or anyone from the codeowners right away, so we can have another look. Thank you

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by joseandrespg** [comment]
Hi @loay and @ssh24. Branch rebased and updated, passing the tests on my side :+1:

**Comment by ssh24** [comment]
@slnode test please

**Comment by loay** [comment]
The tests cause 15 failures in loopback repo .. They are all in the `test/util/model-tests.js` file 

Here are the failures:

```
  1) Model / PersistedModel Model Tests Model.validatesPresenceOf(properties...) Require a model to include a property to be considered valid:
     TypeError: Cannot read property 'last' of undefined
    at Context.<anonymous> (test/util/model-tests.js:70:26)
  

  2) Model / PersistedModel Model Tests Model.validatesLengthOf(property, options) Require a property length to be within a specified range:
     TypeError: Cannot read property 'password' of undefined
    at Context.<anonymous> (test/util/model-tests.js:80:26)
  

  3) Model / PersistedModel Model Tests Model.validatesInclusionOf(property, options) Require a value for `property` to be in the specified array:
     TypeError: Cannot read property 'gender' of undefined
    at Context.<anonymous> (test/util/model-tests.js:89:26)
  

  4) Model / PersistedModel Model Tests Model.validatesExclusionOf(property, options) Require a value for `property` to not exist in the specified array:
     TypeError: Cannot read property 'domain' of undefined
    at Context.<anonymous> (test/util/model-tests.js:102:26)
  

  5) Model / PersistedModel Model Tests Model.validatesNumericalityOf(property, options) Require a value for `property` to be a specific type of `Number`:
     TypeError: Cannot read property 'age' of undefined
    at Context.<anonymous> (test/util/model-tests.js:115:26)
  

  6) Model / PersistedModel Model Tests myModel.isValid() Validate the model instance:
     TypeError: Cannot read property 'age' of undefined
    at Context.<anonymous> (test/util/model-tests.js:125:27)
  

  7) Model / PersistedModel Model Tests myModel.isValid() Asynchronously validate the model:
     TypeError: Cannot read property 'age' of undefined
    at test/util/model-tests.js:133:29
    at ModelConstructor.<anonymous> (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/validations.js:566:11)
    at ModelConstructor.next (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/hooks.js:93:12)
    at ModelConstructor.<anonymous> (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/validations.js:563:23)
    at ModelConstructor.trigger (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/hooks.js:83:12)
    at ModelConstructor.Validatable.isValid (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/validations.js:529:8)
    at Context.<anonymous> (test/util/model-tests.js:131:14)
  

  8) Model / PersistedModel Model.validatesUniquenessOf(property, options) Ensure the value for `property` is unique:
     Uncaught TypeError: Cannot read property 'email' of undefined
    at test/model.test.js:53:29
    at /Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/dao.js:359:9
    at ModelConstructor.<anonymous> (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/validations.js:577:13)
    at ModelConstructor.next (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/hooks.js:93:12)
    at done (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/validations.js:574:25)
    at /Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/validations.js:652:7
    at ModelConstructor.<anonymous> (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/validations.js:433:5)
    at /Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/dao.js:2095:9
    at /Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/node_modules/async/dist/async.js:1012:9
    at /Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/node_modules/async/dist/async.js:359:16
    at iteratorCallback (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/node_modules/async/dist/async.js:935:13)
    at /Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/node_modules/async/dist/async.js:843:16
    at /Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/node_modules/async/dist/async.js:1009:13
    at buildResult (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/dao.js:2061:11)
    at /Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/dao.js:2075:13
    at doNotify (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/observer.js:155:49)
    at Function.ObserverMixin._notifyBaseObservers (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/observer.js:178:5)
    at Function.ObserverMixin.notifyObserversOf (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/observer.js:153:8)
    at Function.ObserverMixin._notifyBaseObservers (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/observer.js:176:15)
    at Function.ObserverMixin.notifyObserversOf (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/observer.js:153:8)
    at Function.ObserverMixin._notifyBaseObservers (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/observer.js:176:15)
    at Function.ObserverMixin.notifyObserversOf (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/observer.js:153:8)
    at Function.ObserverMixin._notifyBaseObservers (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/observer.js:176:15)
    at Function.ObserverMixin.notifyObserversOf (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/observer.js:153:8)
    at withNotify (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/dao.js:2073:17)
    at /Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/dao.js:2014:11
    at /Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/node_modules/async/dist/async.js:1007:9
    at eachOfArrayLike (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/node_modules/async/dist/async.js:940:9)
    at eachOf (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/node_modules/async/dist/async.js:990:5)
    at _asyncMap (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/node_modules/async/dist/async.js:1005:5)
    at Object.map (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/node_modules/async/dist/async.js:995:16)
    at allCb (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/dao.js:2009:13)
    at /Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/connectors/memory.js:512:7
    at node_modules/async-listener/glue.js:188:31
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:122:9)
  

  9) RemoteConnector Model Tests Model.validatesPresenceOf(properties...) Require a model to include a property to be considered valid:
     TypeError: Cannot read property 'last' of undefined
    at Context.<anonymous> (test/util/model-tests.js:70:26)
  

  10) RemoteConnector Model Tests Model.validatesLengthOf(property, options) Require a property length to be within a specified range:
     TypeError: Cannot read property 'password' of undefined
    at Context.<anonymous> (test/util/model-tests.js:80:26)
  

  11) RemoteConnector Model Tests Model.validatesInclusionOf(property, options) Require a value for `property` to be in the specified array:
     TypeError: Cannot read property 'gender' of undefined
    at Context.<anonymous> (test/util/model-tests.js:89:26)
  

  12) RemoteConnector Model Tests Model.validatesExclusionOf(property, options) Require a value for `property` to not exist in the specified array:
     TypeError: Cannot read property 'domain' of undefined
    at Context.<anonymous> (test/util/model-tests.js:102:26)
  

  13) RemoteConnector Model Tests Model.validatesNumericalityOf(property, options) Require a value for `property` to be a specific type of `Number`:
     TypeError: Cannot read property 'age' of undefined
    at Context.<anonymous> (test/util/model-tests.js:115:26)
  

  14) RemoteConnector Model Tests myModel.isValid() Validate the model instance:
     TypeError: Cannot read property 'age' of undefined
    at Context.<anonymous> (test/util/model-tests.js:125:27)
  

  15) RemoteConnector Model Tests myModel.isValid() Asynchronously validate the model:
     TypeError: Cannot read property 'age' of undefined
    at test/util/model-tests.js:133:29
    at ModelConstructor.<anonymous> (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/validations.js:566:11)
    at ModelConstructor.next (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/hooks.js:93:12)
    at ModelConstructor.<anonymous> (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/validations.js:563:23)
    at ModelConstructor.trigger (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/hooks.js:83:12)
    at ModelConstructor.Validatable.isValid (/Users/loay/Desktop/NodeEE/DB/loopback-datasource-juggler/lib/validations.js:529:8)
    at Context.<anonymous> (test/util/model-tests.js:131:14)
  

```

**Comment by loay** [comment]
Also, looking at the content of the pr, I understand that it is a reserved word, but we cannot change it for now, as it will be a breaking change.. I can create an issue to document it but it does not look like we can do these breaking changes now. 

@ssh24 @dhmlau

**Comment by joseandrespg** [comment]
@loay yes, it can be a BC for some, including other loopback repos. 

The option of document the issue would be useful in the meantime. But it will be great if you could plan to fix it on future versions.

**Pull request closed without merging**
