### PR TITLE
EmbedsOne - EmbedsMany update only properties sent

### PR DESCRIPTION
**Pull request by mitsos1os**
As discussed in https://github.com/strongloop/loopback/issues/1629 embedded document should comply with general process of updating documents. Only fields specified in update data should be updated and not whole embedded documents replaced...

### CODE REVIEW

**Comment by mitsos1os** [comment]
Again Commit Linter is failing without error while running npm run lint on the repository completes successfully......

**Comment by loay** [comment]
@mitsos1os Having a look. Thanks.

**Comment by loay** [comment]
I think the linting issue is there in your commit title/message : `EmbedsOne - EmbedsMany update only properties sent and not whole embe…`  which produced this error message: 

```
First line should be 50 characters or less (saw 82)```

**Comment by mitsos1os** [comment]
@loay you were right it was the commit message title. I have also updated the branch to be up to date. Thanks

**Comment by mamartins** [comment]
Same kind of problems happen when you simply use an updateAttributes on one object, they replace fields that are not on the updateAttributes passed object/no validation done so you can even add fields that are not on the model

**Comment by mitsos1os** [comment]
Hi @loay  Any update on this pull request?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by mitsos1os** [comment]
Please tell me what is wrong with the commit linter again... If you agree I would like this to be merged... It is quite important....

**Comment by loay** [comment]
@slnode test please

**Comment by loay** [comment]
@mitsos1os 
I see that you fixed the commit message. Also, this PR needs to be rebased. 
I put the PR into test now and I will wait to see. I will get back to you soon. Thanks

**Comment by mitsos1os** [comment]
@loay I have rebased the pull request again. It is now up to date

**Comment by loay** [comment]
@mitsos1os Yeah it is rebased now. 
One last step, please make sure you squash the 2nd commit and to choose the 2nd commit's message to be used as the first one is still failing the formatting test (too long). Thanks. 

@raymondfeng / @superkhau  Can you please approve ? LGTM.

**Comment by mitsos1os** [comment]
@loay Just changed commit message...

**Comment by BoLaMN** [comment]
What about empty arrays? As they seem to destroy the child embed if not populate in the query

**Comment by jannyHou** [comment]
@slnode test please

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
