### PR TITLE
Update dependencies to latest 

### PR DESCRIPTION
**Pull request by bajtos**
Production dependencies:

- `loopback-connector` to  `^5.0.0` - see [release notes](https://github.com/strongloop/loopback-connector/blob/master/CHANGES.md#2020-08-28-version-500)
- `strong-globalize` to `^6.0.5` - see [release notes](https://github.com/strongloop/strong-globalize/blob/master/packages/runtime/CHANGELOG.md#600-2020-04-10)
- `uuid` to `^8.3.1` - see [release notes](https://github.com/uuidjs/uuid/blob/master/CHANGELOG.md#800-2020-04-29)

Dev dependencies:

- `eslint` to `^7.11.0`
- `mocha` to `^8.1.3`
- `typescript` to `^4.0.3`

Close https://github.com/strongloop/loopback-connector-postgresql/issues/463

/cc @billinghamj 

## Checklist

- [x] [Sign off your commits](https://loopback.io/doc/en/contrib/code-contrib.html) with DCO (Developer Certificate of Origin)
- [x] `npm test` passes on your machine
- New tests added or existing tests modified to cover all changes
- Code conforms with the [style guide](https://loopback.io/doc/en/contrib/style-guide-es6.html)
- [x] Commit messages are following our [guidelines](https://loopback.io/doc/en/contrib/git-commit-messages.html)

### CODE REVIEW

**Review by dhmlau — APPROVED** [review]
@bajtos, thanks for updating the dependencies. Your changes LGTM. Please investigate the CI failure, I'm not sure if it's related to this change though. Thanks.

**Comment by bajtos** [comment]
Let's see.


> [cis-jenkins] downstream: loopback-connector-mongodb@master — Failed! (8487ee1) [Details](https://cis-jenkins.swg-devops.com/job/ds/job/loopback-connector-mongodb%7Emaster/31/console)

```
1) method level options
        should create and update an item with a field containing a JSON with a property using `.` :
      MongoError: The dotted field 'player.lives' in 'playerInfo.player.lives' is not valid for storage.
```

Seems unrelated to my changes.

> [cis-jenkins] downstream: loopback-connector-oracle@master — Failed! (8487ee1) [Details](https://cis-jenkins.swg-devops.com/job/ds/job/loopback-connector-oracle%7Emaster/31/console)

```
1) "before all" hook in "{root}":
      Error: ORA-12154: TNS:could not resolve the connect identifier specified
```

Looks like our testing database is down, do we know how to bring it up?

> [cis-jenkins] downstream: loopback-connector-postgresql@3.x — Failed! (8487ee1) [Details](https://cis-jenkins.swg-devops.com/job/ds/job/loopback-connector-postgresql%7E3.x/31/console)

I see lots of timeout errors:

```
Uncaught AssertionError: expected Error { message: 'Timeout in connecting after 5000 ms' } to not exist
```

Let me restart the build to see if this particular problem goes away.

**Comment by bajtos** [comment]
@slnode test please

**Comment by dhmlau** [comment]
For oracle database, I'm not sure. I initially thought we start a docker image with oracle db for CI. 🤷‍♀️ 
Perhaps @rmg  might know?

**Comment by bajtos** [comment]
I am going to ignore downstream test failures, they seem unrelated to my changes.

@dhmlau perhaps we can open one or more follow-up issues to investigate and fix those problems?

**Pull request merged**
