### PR TITLE
Takeover: 1101

### PR DESCRIPTION
**Pull request by superkhau**
Connect to #1101

### CODE REVIEW

**Comment by superkhau** [comment]
Created issue for MySQL failure at https://github.com/strongloop/loopback-connector-mysql/issues/196.

The rest are unrelated.

**Comment by superkhau** [comment]
- DB2 is unrelated and a known failure and being worked on by @qpresley 
- DB2z won't work until [we get a dedicated CI instance](https://github.com/strongloop-internal/scrum-loopback/issues/1051) -- created [PR to skip tests](https://github.com/strongloop/loopback-connector-db2z/pull/10) until we figure out the situation there.
- mqlight is being skipped too until we configure CI properly too
- MySQL issue is created (been around for awhile now) -- TOB/Majored https://github.com/strongloop/loopback-connector-mysql/issues/196
- strong-arc has been looked into by @bajtos -- I believe its a sub dep of that project (strong-mesh-models) or something that needs some work on -- ignoring this one

**Comment by superkhau** [comment]
test please

**Comment by superkhau** [comment]
test please

**Comment by superkhau** [comment]
test please

**Comment by timdp** [comment]
Out of curiosity, will this also make it into 2.x or is that in support mode now that 3.0.0 is out?

**Comment by bajtos** [comment]
@superkhau 

> Takeover: 1101

That pull request title is useless. Please use a more descriptive name in the future.

You also forgot to squash the commits before landing, the git history is rather messy now :(

screen shot 2016-09-23 at 10 33 11

**Comment by bajtos** [comment]
> Out of curiosity, will this also make it into 2.x or is that in support mode now that 3.0.0 is out?

I think we should back-port this to 2.x, could you @superkhau please take care of that?

3.0.0 is a release candidate, it hasn't been officially release yet.

**Comment by superkhau** [comment]
>You also forgot to squash the commits before landing, the git history is rather messy now :(

Yeah, suck because it makes it harder to cherry pick for the backport too. :( I squashed the backported commits though.

**Pull request merged**
