### PR TITLE
support: add install-test-deps.js

### PR DESCRIPTION
**Pull request by bajtos**
This script should be used by connectors to install dependencies needed to run the shared test suite.

Usage: Add an npm "install" scripts with the following contents:

    node -e "require('loopback-datasource-juggler/support/install-test-deps')"

/to @raymondfeng please review

### CODE REVIEW

**Comment by raymondfeng** [comment]
I don't think the script will work on Windows.

**Comment by bajtos** [comment]
> I don't think the script will work on Windows.

Why it should not work? It works for me on Windows 8 in VirtualBox:

```
C:\src\loopback-datasource-juggler (feature/install-test-deps)
λ node support\install-test-deps.js
Installing dev dependencies in C:\src\loopback-datasource-juggler

C:\src\loopback-datasource-juggler (feature/install-test-deps)
λ ls node_modules\
async  bluebird  debug  inflection  lodash  loopback-connector  mocha  qs  should  traverse

**Comment by raymondfeng** [comment]
Never mind. I just realized that child_process.exec() is to invoke a shell script.

**Comment by raymondfeng** [comment]
I still don't like the fact that each connector will have to mess around package.json with the install script (node -e "require('loopback-datasource-juggler/support/install-test-deps')"). These scripts are evil :-).

What about making the logic in the install script of `loopback-datasource-juggler`?

**Comment by raymondfeng** [comment]
I didn't have a chance to test it out with loopback-datasource-juggler but I fixed most connectors' dev deps.

**Comment by bajtos** [comment]
I'm ok with whatever works best for you.

**Pull request closed without merging**
