### PR TITLE
Fix polymorphic hasMany inverse relation

### PR DESCRIPTION
**Pull request by iamraphson**
### Description

This is just a fix for polymorphic hasMany Inverse relation for 3.x or master. PR was raised for this fix but It was merged into 2.x using this PR https://github.com/strongloop/loopback-datasource-juggler/pull/1296 but it should be available in 3.x or master

#### Related issues

The issue was raised here https://github.com/strongloop/loopback-datasource-juggler/issues/1079

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by jannyHou** [comment]
@slnode test please

**Comment by nitro404** [comment]
Looks good to me, can you please rebase this pull request with the latest changes on the target branch? Thanks!

**Comment by iamraphson** [comment]
@nitro404 done

**Comment by nitro404** [comment]
Hmm, this does not seem to be properly re-based. It looks like you tried to merge it instead and brought some commits from elsewhere along with it. You're going to need to force push a new branch on top of this one pointing to the head of loopback/master with your commit properly cherry picked onto it. When you've done this correctly you shouldn't have any conflicts and there should be a single commit in your pull request. There should be some tutorials for how to do this online.

**Comment by iamraphson** [comment]
Hey @nitro404 ,i created a new PR https://github.com/strongloop/loopback-datasource-juggler/pull/1589 ..You can close this and review the other one.

**Comment by nitro404** [comment]
@iamraphson Can you please close this pull request? Thank you!

**Comment by iamraphson** [comment]
@nitro404 what can I do to get this PR merged??

**Comment by nitro404** [comment]
This is a duplicate pull request, your other one is still open and requires attention. I do not have the ability to accept pull requests, a project collaborator must review and accept it.

**Comment by iamraphson** [comment]
ok @nitro404 ,let me close this and make sure,we merge the other PR

**Pull request closed without merging**
