### PR TITLE
Added strict filter condition

### PR DESCRIPTION
**Pull request by jsheely**
I want to be able to filter the out the properties given to a model from either inputs in remoting or outputs from juggler instead of throwing an error.

Small code code

if(strict !=='filter'){
   this.__unknownProperties.push(p);
}

@ssh24

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ssh24** [comment]
@jsheely Could you please give me access to your fork so I can work around your branches? Looks like you have rebased your `master` branch totally wrong and it requires some reverts. More info on how to give me access to your fork: https://github.com/blog/2247-improving-collaboration-with-forks

**Comment by jsheely** [comment]
Sure. I just checked out ```source/master```. Created a branch. Made change. submitted pull request. 

My version of master is different due to some custom changes that I've had to make for various other reasons. I didn't think my local/master would be effected since I pulled source/master.

**Comment by ssh24** [comment]
Well, well. That is the problem here. **Do not ever use a fork branch's master to commit changes**. It will give tremendous amount of headache when rebasing the forked branch's master against the head master. The clean way to do any contribution is to:
1. Fork the repo you want to contribute to
2. Create a branch on the fork repo (Remember: Do not start committing change on master)
3. Commit changes to the forked repo

Now, you will have all your changes in your customized branch in your fork per contribution you make. For each contribution when you do a PR for it, that branch has to be rebased against the fork branch's master and in turn the fork branch's master needs to be rebased against the head master (in this loopback-datasource-juggler's master).

To rebase follow these steps. Assuming you are on your branch:
```
1. git checkout master
2. git remote add upstream <head_master_repo>
3. git fetch upstream
4. git rebase upstream/master
5. git push origin master
6. git checkout <my_branch>
7. git fetch
8. git rebase -i origin/master
9. git push origin <my_branch>
```

I will try to fix your problem, but I cannot guarantee a fix for it. If it does not work I will create a PR myself, however all credit goes to you!

**Comment by ssh24** [comment]
Closing this as per #1273

**Pull request closed without merging**
