### PR TITLE
Indicate result of destroyById/protototype.destroy

### PR DESCRIPTION
**Pull request by bajtos**
Return `info.count` to the callback to indicate whether the model instance was deleted or not. When `options.strict` is true, return 404 error when the model instance was not found.

See #521 for the initial solution.

/to @raymondfeng @fabien please review

### CODE REVIEW

**Comment by raymondfeng** [comment]
1. What's the implication of REST mapping? At the moment, the `deleteById` reports http status code 204. Do we need to introduce a flag to keep it backward compatible?

2. What's the response from `deleteAll()`?

**Comment by bajtos** [comment]
@raymondfeng thank you for thoughtful comments.

> What's the implication of REST mapping? At the moment, the deleteById reports http status code 204. Do we need to introduce a flag to keep it backward compatible?

There is already a new flag `options.strict` for that. 404 is returned only when this flag is set.

Note that the `options` object is not yet exposed via REST, thus REST clients cannot enable this behaviour yet. To fix this, we need to modify remoting metadata in the main loopback module.

> What's the response from deleteAll()?

The callback receives `(err, info)` from the underlying connector. `deleteAll` is not exposed via REST by default, therefore the HTTP response of `deleteAll` is not a part of loopback API contract IMO.

LGTY now? Is there anything else to address/discuss?

**Comment by fabien** [comment]
> Note that the options object is not yet exposed via REST, thus REST clients cannot enable this behaviour yet. To fix this, we need to modify remoting metadata in the main loopback module.

@bajtos @raymondfeng if I gather correctly, the plan would be to expose the optional `options` of methods like `find` or `create` to the REST API as well? If so, then this would probably be a bad idea. I can think of a few ways of how this could be a security risk, even (flag to bypass validation etc.).

Instead I would propose to allow one to hard-code or otherwise explicitly set which option keys to accept, or to even declare this options object with fixed values. In other words, prevent them from being set through REST (or any other remoting adapter). For example, pseudo code:

```Widget.setOptionsFor('delete', { strict: true })```

**Comment by bajtos** [comment]
> if I gather correctly, the plan would be to expose the optional options of methods like find or create to the REST API as well? If so, then this would probably be a bad idea. I can think of a few ways of how this could be a security risk, even (flag to bypass validation etc.).

+1 for NOT exposing `options` object as it is.

I am wondering if I should perhaps rework this PR and move per-method `options.strict` to a model-level setting `strictDelete`?

**Comment by fabien** [comment]
@bajtos having a `strictDelete` model-level settings sounds great

**Comment by raymondfeng** [comment]
> The callback receives (err, info) from the underlying connector. deleteAll is not exposed via REST by default, therefore the HTTP response of deleteAll is not a part of loopback API contract IMO.

I would like to have a way to expose the deleted `count` over REST. Maybe under a flag for LB 2.x.

**Comment by bajtos** [comment]
> having a strictDelete model-level settings sounds great

Reworked, PTAL again.

> I would like to have a way to expose the deleted count over REST. Maybe under a flag for LB 2.x.

Sounds good to me. Such change must be implemented in loopback, not juggler, therefore it's out of scope of this patch.

 @fabien @raymondfeng  LGTY now?

**Comment by raymondfeng** [comment]
LGTM

**Pull request merged**
