### PR TITLE
Fix model definition column names method

### PR DESCRIPTION
**Pull request by destillat**
#### Related issues

- None

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by destillat** [comment]
ok to test

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@destillat Could you please rebase your branch so we could proceed with the landing of this PR?

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@destillat Thank you for the contribution!

**Pull request merged**
