### PR TITLE
Notify find 2.x

### PR DESCRIPTION
**Pull request by Amir-61**
Notify find 2.x

We already implemented `notify` for `find` on master branch; however the implementation of `find` is very different from the one on `2.x`, hence a simple cherry-pick was not going to work; this patch implements `notify` for `2.x`

### CODE REVIEW

**Comment by Amir-61** [comment]
@slnode test please

**Comment by bajtos** [comment]
FWIW, here is the original pull request against the master branch: https://github.com/strongloop/loopback-datasource-juggler/pull/898

**Comment by bajtos** [comment]
The patch LGTM, :shipit:

**Comment by Amir-61** [comment]
Implement `notify` for find method [2.x]

**Pull request merged**
