### PR TITLE
Fix up #1109

### PR DESCRIPTION
**Pull request by Amir-61**
Fixup #1109 

/to: @superkhau

### CODE REVIEW

**Comment by superkhau** [comment]
Please change the commit message to something more descriptive before landing.

**Comment by Amir-61** [comment]
@superkhau @davidcheung 

>Please change the commit message to something more descriptive before landing.

I could not think anything better than`Fix up #1109` as the commit description. Ok I'm fine, if you have a better suggestion, please let me know and I'll change it accordingly.

**Comment by Amir-61** [comment]
@slnode test please

**Comment by davidcheung** [comment]
@Amir-61 i would write something like 
>make variable names more clear

or 

>coding style clean up

or 

> change variable name

so if someone does `git log` they dont need to go into the commit to see what happened

**Comment by superkhau** [comment]
@Amir-61 

```
Code cleanup

Leftover code cleanup from #1109.

* Removed extra blank line

* Changed variable name `u` to `user` a test case
```

**Comment by rmg** [comment]
@slnode test please

**Comment by Amir-61** [comment]
@slnode test please

**Comment by Amir-61** [comment]
@slnode test please

**Comment by Amir-61** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by Amir-61** [comment]
@rmg unfortunately re-trigger build did not help after clearing registry on you end; I do another build, hopefully it passes now with out the following failure:
```
npm ERR! 404 no such package available : karma
npm ERR! 404 
npm ERR! 404 'karma' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'loopback'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by Amir-61** [comment]
@slnode test please

**Comment by Amir-61** [comment]
@slnode test please

**Pull request merged**
