### PR TITLE
Add test support for Cassandra connector

### PR DESCRIPTION
**Pull request by Setogit**
### Description

Add support for Cassandra connector

#### Related issues

- None

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by kjdelisle** [comment]
Just gotta fix the typo in the commit message (for patch notes) and LGTM

**Comment by Setogit** [comment]
@slnode test please

**Comment by ssh24** [comment]
I wonder why was this merged with CI having so many failures? `Postgresql` failure is expected because of the CI database for postgres having timeout errors but here we have more than just postgres failing.
add test support for cassandra connector by setogit pull request 1310 strongloop-loopback-datasource-juggler google chrome today at 7 49 57 pm

**Comment by Setogit** [comment]
Merged with downstream connector failures because miscommunication between me and Kevin.  

Kevin mentioned that the failure had been unrelated.  I assumed all the connector failures we see above.  Kevin meant just postgresql failure.

I'm looking at others and will revert or fix them.

**Pull request merged**
