### PR TITLE
Fix #1079 - Polymorphic hasMany inverse relation in include filter

### LINKED ISSUE #1079: Polymorphic hasMany inverse relation doesn't work on include filter
Using an include filter where the included relation is a polymorphic hasMany with invert set to true does not correctly take into account the invert option when figuring out which model to query, causing no records for the relation to return.

Given these model definitions:

``` js
Picture = db.define('Picture', { name: String });
Author = db.define('Author', { name: String });
PictureLink = db.define('PictureLink', {});

Author.hasMany(Picture, { through: PictureLink, polymorphic: 'imageable', invert: true });
Picture.hasMany(Author, { through: PictureLink, polymorphic: 'imageable' });
```

When running the below code snippet an empty array will always return for pictures, even if it actually contains valid entries:

``` js
Author.findOne({ include: 'pictures' }...); // this will not work, pictures will always be empty
```

However when querying the relation directly like this, things work fine:

``` js
// Given an author instance...
author.pictures(); // this will work, pictures will include all pictures
```

Here is the failing test case I wrote which shows this behaviour. Please correct me if I have misunderstood how the inverse relations should work:

``` js
  describe('polymorphic hasMany', function() {
    before(function(done) {
      Picture = db.define('Picture', { name: String });
      Author = db.define('Author', { name: String });
      PictureLink = db.define('PictureLink', {});

      Author.hasMany(Picture, { through: PictureLink, polymorphic: 'imageable', invert: true });
      Picture.hasMany(Author, { through: PictureLink, polymorphic: 'imageable' });

      db.automigrate(['Picture', 'Author', 'PictureLink'], done);
    });

    it('should properly query through an inverted relationship', function(done) {
      Author.create({ name: 'Steve' }, function(err, author) {
        author.pictures.create({ name: 'Steve pic 1' }, function(err, pic) {
          Author.findOne({ include: 'pictures' }, function(err, author) {
            if (err) { return done(err); }
            assert.equal(author.pictures().length, 1);
            assert.equal(author.pictures()[0].name, 'Steve pic 1');
            done();
          });
        });
      });
    });
  });
```

This issue might be related to #927, but I'm not sure.

### PR DESCRIPTION
**Pull request by alexpls**
This is a proposed fix to #1079. For more details of the issue please check out the issue.

Note I've targeted this fix to the `2.x-latest` branch. I'm not fully familiar with the v3 source code, but I believe this fix should be applied to the v3 branch as well. Happy to raise another PR for this if you agree.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by jannyHou** [comment]
@slnode test please

**Comment by Amir-61** [comment]
@slnode test please

**Comment by alexpls** [comment]
@slnode test please

**Comment by devpascoe** [comment]
Really need this 😆❤️

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@alexpls The change LGTM. while the test case should be in file `test/relation.test.js`:https://github.com/strongloop/loopback-datasource-juggler/blob/master/test/relations.test.js could you move it to the right place? Thanks.

**Comment by jannyHou** [comment]
@slnode test please

**Comment by alexpls** [comment]
@jannyHou Thanks! I've updated the PR with these changes:

- Moved the test case to `test/relation.test.js`
- Rebased to the tip of the `2.x-latest` branch
- Resolved some eslint warnings

All these changes have been squashed into one commit so it keeps the git history clean.

Let me know if anything else needs to be changed!

**Comment by jannyHou** [comment]
@alexpls Cheers the pr landed but sorry I made a mistake...the pr should be checked into 2.x instead of 2.x-latest....could you backport it to 2.x? Or if you don't mind I can do the backport for you.

**Comment by alexpls** [comment]
@jannyHou I'm happy for you to do the backport - thanks!

**Pull request merged**
