### PR TITLE
Typo on README.md

### PR DESCRIPTION
**Pull request by jpventura**
### Description
Fix typo on README.md

#### Related issues
NONE

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by virkt25** [comment]
ok to test

**Comment by jpventura** [comment]
@virkt25, is master branch passing? Only the README file was changed on this PR.

**Comment by virkt25** [comment]
@jpventura it should be. The reason for the current failure is out CI server is down atm. Will be back up Monday and I'll retrigger the test at that point. I don't foresee any issue with your PR but we need to wait till Monday.

**Comment by jpventura** [comment]
@dhmlau should I PR again to trigger the integration tests?

**Comment by dhmlau** [comment]
@jpventura , don't think it would help.  Let me kick off the test again.  Although I don't think the failure is caused by your PR, I'd rather not to merge with failure in CI.  Hope you understand. :)

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
I'm force merging it because the typo fix in the README is not the cause of the CI failure and @jannyHou had found the root cause.  

@jpventura  thanks for your contribution!

**Pull request merged**
