### PR TITLE
Add test coverage for `validatesInclusionOf`

### PR DESCRIPTION
**Pull request by Overdrivr**
### Description

Add missing tests for Validatable.validatesInclusionOf method

#### Related issues

- #1154 

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ssh24** [comment]
@Overdrivr Could you please rebase your branch?

**Comment by Overdrivr** [comment]
@ssh24 I have made a few extra changes to be consistent with #1248 , It's also rebased now ;)

**Comment by ssh24** [comment]
@slnode ok to test

**Comment by ssh24** [comment]
@Overdrivr Thank you for the contribution!

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Pull request merged**
