### PR TITLE
fix datetype error on included model

### PR DESCRIPTION
**Pull request by hiddestokvis**
This is a fix for the issue described in:
https://github.com/strongloop/loopback-datasource-juggler/issues/717

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by loay** [comment]
@slnode test please

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by loay** [comment]
hi @hiddestokvis 
Can you please rebase the code as well as adding a unit test, so we can try to re-test it here? Thanks

**Comment by bajtos** [comment]
Closing as abandoned.

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
