### PR TITLE
Backport: Add ilike and nilike operators

### LINKED ISSUE #633: Pass through ilike and nilike parameters so they can be handled by connectors
Every application needs to be able to search without case sensitivity. Other than regular expressions (not always supported) there isn't a good way to do this. See PR for fixing this in Postgres connector (https://github.com/strongloop/loopback-connector-postgresql/pull/93). This patch needs to be applied to the juggler as well.

### PR DESCRIPTION
**Pull request by superkhau**
Closes #633

Backport of #1091 

cc @bajtos @duffn

### CODE REVIEW

**Comment by superkhau** [comment]
Submitted downstream fix for gateway-director-manager: https://github.ibm.com/apimesh/gateway-director-management-interface/pull/12

cloudant@2.x needs linting -- @jannyHou PTAL
dashdb is a known failure
db2@2.x is a known failure
mysql@2.x is failing due to truncation issue still -- @loay I thought you took care of this one?
oracle@2.x is a known failure
con-soap looks new -- @rashmihunt PTAL
con-swagger looks new -- @gunjpan PTAL
ios-codegen is unrelated
arc is failing to install deps -- ignoring (i think this one is a known issue)

Merging.

**Comment by gunjpan** [comment]
@superkhau : CI failure for `lb-conn-swagger` is fixed. (there is a [refactor story](https://github.com/strongloop/loopback-connector-swagger/issues/140) for making it more robust).

**Comment by superkhau** [comment]
@gunjpan Link is broken -- and when you say fixed, was it before my CI results above?

**Comment by gunjpan** [comment]
@superkhau : updated link. 
>was it before my CI results above?

No.

**Comment by superkhau** [comment]
@gunjpan Cool, thanks for taking care of it. :+1:

**Pull request merged**
