### PR TITLE
Promisify all 'discover' methods

### PR DESCRIPTION
**Pull request by PradnyaBaviskar**
Connect https://github.com/strongloop/loopback/issues/418

Promisify following methods -
  1. discoverModelDefinitions
  2. discoverModelProperties
  3. discoverPrimaryKeys
  4. discoverForeignKeys
  5. discoverExportedForeignKeys
  6. discoverSchema
  7. discoverSchemas

@bajtos - can you please review?

### CODE REVIEW

**Comment by bajtos** [comment]
Nice, LGTM.

@raymondfeng You are more familiar with autodiscovery, could you please take a look too? Especially on the unit tests.

**Comment by raymondfeng** [comment]
The `options` argument is optional. Most of the connectors have the following code:
```
if (cb === undefined && typeof options === 'function') {
      cb = options;
      options = {};
    }
    options = options || {};
```

We need to normalize the args before your changes. 

@PradnyaBaviskar Can you fix that?

**Comment by PradnyaBaviskar** [comment]
@raymondfeng,

> We need to normalize the args before your changes.

Just so that I understand this better, before we do `cb = cb || utils.createPromiseCallback();`, in each `discover*()` method, I should add

```
if (cb === undefined && typeof options === 'function') {
      cb = options;
      options = {};
    }
    options = options || {};
```

Is this correct understanding?

**Comment by raymondfeng** [comment]
@PradnyaBaviskar Yes.

**Comment by PradnyaBaviskar** [comment]
Done with normalizing the args.

**Comment by raymondfeng** [comment]
@PradnyaBaviskar Thanks. Can you also add a test to cover the case where `options` is not present?

**Comment by PradnyaBaviskar** [comment]
Done - added tests to cover the case of missing `options` parameter.

**Comment by raymondfeng** [comment]
ok to test

**Pull request merged**
