### PR TITLE
 Validation only occurs at root level when there are nested Models #136

### PR DESCRIPTION
**Pull request by komarik0**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by raymondfeng** [comment]
@komarik0 Thank you for the patch. Can you add a test case?

**Comment by komarik0** [comment]
@raymondfeng, done. tests were added.

**Comment by bajtos** [comment]
Isn't this the same bug I pointed out in https://github.com/strongloop/loopback-datasource-juggler/pull/516#discussion_r26821273? IIUC, the validations are triggered when you e.g. add a new embedded model instance, but they are not triggered when you update an existing instance.

I think @fabien should review this patch too, he is the author of embedded relations.

**Comment by raymondfeng** [comment]
@fabien ping

**Comment by bajtos** [comment]
@komarik0 sorry for the long delay. Are you still interested in getting this patch landed?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
I am closing this patch as abandoned. Feel free to reopen if you get time to address our comments above.

**Pull request closed without merging**
