### PR TITLE
Prevent JSON Object or ANY type explode when queried

### PR DESCRIPTION
**Pull request by yshing**
#### Related issues

- #1434 

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ssh24** [comment]
@yshing Can you please close this PR? Looks the fix was landed in https://github.com/strongloop/loopback-datasource-juggler/pull/1444
Also see https://github.com/strongloop/loopback-datasource-juggler/issues/1434

**Comment by b-admike** [comment]
@yshing Closing this PR in favour of https://github.com/strongloop/loopback-datasource-juggler/pull/1443#issuecomment-332356671. Feel free to let us know if you think it should be re-opened. Thank you for your contribution!

**Pull request closed without merging**
