### PR TITLE
Fix error assertion

### PR DESCRIPTION
**Pull request by loay**
### Description
Fix assertion statements and linting errors. 

#### Related issues

to complement pr #https://github.com/strongloop/loopback-datasource-juggler/pull/1304

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by loay** [comment]
@slnode test please

**Comment by ssh24** [comment]
MSSQL failure is expected. We opened up a new shared db instance for cis-jenkins and it is failing to connect. Working on that with @rmg for fix.

**Comment by loay** [comment]
@ssh24 Thanks

**Comment by loay** [comment]
@slnode test please

**Pull request merged**
