### PR TITLE
backport #1782 to 3.x

### PR DESCRIPTION
**Pull request by mitsos1os**
Backport #1782 to 3.x branch
## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-datasource-juggler) 👈

- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](https://loopback.io/doc/en/contrib/style-guide-es6.html)
- [x] Commit messages are following our [guidelines](https://loopback.io/doc/en/contrib/git-commit-messages.html)

### CODE REVIEW

**Comment by dhmlau** [comment]
Changes are the same as 4.x.  Let's wait for CI to run.

**Comment by dhmlau** [comment]
@slnode test please

**Comment by emonddr** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@strongloop/loopback-maintainers , could you please review this PR?  
- downstream failure seems to be random.  It was `loopback-connector-mysql` this time but it was `loopback-connector-dashdb` in the previous run
- not sure why CI against Node.js 6 was being run because of https://github.com/strongloop/loopback-datasource-juggler/blob/3.x/package.json#L18-L20.

**Comment by dhmlau** [comment]
@raymondfeng @jannyHou, do you think it's ok to force merge this PR? See my [above comment](https://github.com/strongloop/loopback-datasource-juggler/pull/1785#issuecomment-545134108).

**Comment by dhmlau** [comment]
Confirmed with @jannyHou, it's ok to force merge.

**Comment by dhmlau** [comment]
`loopback-datasource-juggler@3.33.2` has been released.

**Comment by FedericoMassaioli** [comment]
Hi, unfortunately this back-port broke like, nlike, ilike and nilike operators for SQL DBs (PostgreSQL in my case) as the usual query strings using %, like those in LB 3.x documentation are deemed invalid and 'sanitized', causing empty results in whatever query.

**Comment by dhmlau** [comment]
@FedericoMassaioli, sorry to hear that. Could you please open a new issue to discuss? Thanks.

**Comment by dhmlau** [comment]
@mitsos1os, I wonder how it can slip through CI (looking at the tests in CI, they seemed to be passing as well). Could you please take a look? Thanks.

**Comment by mitsos1os** [comment]
@dhmlau I am not sure how it slipped through... Yes I will take a look and let you know under issue #1869

**Comment by FedericoMassaioli** [comment]
@dhmlau the case of an SQL like query containing characters that trigger `escapeRegEx()` is not covered in b925e8c.

It also looks like LB3.x unit tests only exercise memory, mock, and test connectors, no SQL connector. The SQLite 3 connector configured to use memory could be good enough to these purposes.

**Pull request merged**
