### PR TITLE
Add test for updateOrCreate[2.x]

### PR DESCRIPTION
**Pull request by Amir-61**
@superkhau  @loay 
I had forgot to backport https://github.com/strongloop/loopback-datasource-juggler/pull/989. This patch backports the patch to `2.x`

* Add test for updateOrCreate when id is not autogenerated Id

Connect to https://github.com/strongloop/loopback-datasource-juggler/pull/989

/to: @superkhau @0candy @loay

/cc: @bajtos

### CODE REVIEW

**Comment by superkhau** [comment]
@Amir-61 Please add the link to the PR to backport in the commit body.

**Comment by Amir-61** [comment]
@slnode test please

**Comment by Amir-61** [comment]
@slnode test please

**Comment by Amir-61** [comment]
@slnode test please

**Pull request merged**
