### PR TITLE
[DO NOT MERGE] 2.x

### PR DESCRIPTION
**Pull request by superkhau**
# DO NOT MERGE/CLOSE

This is the official branch for 2.x backports.

### CODE REVIEW

**Comment by bajtos** [comment]
I am rather confused, I would swear I have already created this branch back in December, when I was starting 3.0 development on master.

@superkhau please take a look at other commits on the master branch since Dec 22nd, I think some of them should be back-ported - e.g. 93c9f63 via #809.

@Amir-61 please back-port your PR #815 to 2.x too.

**Comment by Amir-61** [comment]
Hi @bajtos,

Simon and I cherry-picked [#815](https://github.com/strongloop/loopback-datasource-juggler/pull/815) into `2.x`; please see [commits on branch 2.x](https://github.com/strongloop/loopback-datasource-juggler/commits/2.x); Isn't that what you are looking for?

Thanks :-)

**Comment by superkhau** [comment]
@bajtos I backported a few more commits into the 2.x branch (including the ones needed by @Amir-61). Do you need the bluebird and the ones you merged in too? I'm not sure how to tell what needs to be backported or not. More specifically, I didn't backport https://github.com/strongloop/loopback-datasource-juggler/pull/796 and https://github.com/strongloop/loopback-datasource-juggler/pull/790.

**Comment by Amir-61** [comment]
>@bajtos I backported a few more commits into the 2.x branch (including the ones needed by @Amir-61). Do you need the bluebird and the ones you merged in too? I'm not sure how to tell what needs to be backported or not. More specifically, I didn't backport #796 and #790.

It looks good...

**Pull request closed without merging**
