### PR TITLE
Added unit tests specific to DateType where null

### PR DESCRIPTION
**Pull request by pastcompute**
### Description

Unit test for where null and not null against Date types.

Regression test for #1328 and #1334

#### Related issues

- None

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by pastcompute** [comment]
Wrong branch, sorry

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ssh24** [comment]
@slnode ok to test

**Comment by ssh24** [comment]
@pastcompute Updated your test cases a bit to take care of other connectors which does not support `null` queries. Please pull latest from your branch.

@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Pull request merged**
