### PR TITLE
Revert ""Near" fix for where clauses"

### PR DESCRIPTION
**Pull request by ssh24**
PR to revert back #1216. `CIS-Jenkins` was down when that PR was merged hence failures regarding other connector was not captured.

### CODE REVIEW

**Comment by ebarault** [comment]
Are there any failure with other connectors?

**Comment by kjdelisle** [comment]
@ebarault It was causing failures in a large number of connectors, such as oracle, mssql, dashdb, etc...

**Comment by kjdelisle** [comment]
@ssh24 will work with you to re-land this PR in a form that works for the other connectors. For the time being, since this is blocking other major PRs, I'm going to commit this revert.

**Comment by ssh24** [comment]
@ebarault Please use `fix/geo.nearFilter-deep` branch on your fork and create a new PR. Please assign me to it and we can work on it to get it working with other connectors.

**Comment by ebarault** [comment]
Ok. Please give me details on what was failing

**Comment by ssh24** [comment]
@ebarault Create a new PR from that branch and we can work it out there. 

**Long story short**: a bunch of downstream tests were failing on the connectors because of the updated `geoNear` logic on #1216.

**Pull request merged**
