### PR TITLE
Fix test case typo

### PR DESCRIPTION
**Pull request by supasate**
Fix a test case that coerces date types but it is incorrectly described to boolean types.

Signed-off-by: Supasate Choochaisri <supasate.c@gmail.com>

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by Amir-61** [comment]
Thanks for contribution!

**Comment by Amir-61** [comment]
@supasate Could you also send a patch against `2.x` branch?

**Comment by supasate** [comment]
Done. But I'm not sure I did something wrong. (Never send a PR to other branch before). I see several commits and conversation containing in my new PR #1017. Please advise @Amir-61.

**Comment by supasate** [comment]
Oh, I think that is caused by sending a PR based on master branch. I need to checkout 2.0 and apply my change on it before sending a PR, right?

**Comment by Amir-61** [comment]
nvm I did it by this PR: https://github.com/strongloop/loopback-datasource-juggler/pull/1018

Thanks!

**Pull request merged**
