### PR TITLE
Disallow regexp arrays for coerce

### PR DESCRIPTION
**Pull request by landofcash**
### Description
Fixes inq where to allow regexp arrays

#### Related issues

- None

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ssh24** [comment]
@landofcash Could you please sign the CLA? Also please add some unit tests so that future regressions can be caught.

**Comment by ssh24** [comment]
@landofcash Thank you for signing the CLA.

Could you please add some unit tests for this patch so we can proceed with the landing of this PR?

**Comment by superkhau** [comment]
@slnode test please

**Comment by landofcash** [comment]
test added

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@landofcash Thank you for the contribution! PR is ready to land.

**Pull request merged**
