### PR TITLE
Fix null conversion to "null" string

### PR DESCRIPTION
**Pull request by gp27**
#### Related issues

- https://github.com/strongloop/loopback/issues/1819

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by kjdelisle** [comment]
@slnode test please

**Comment by BuzkoYaroslav** [comment]
Does this PR have a chance to be approved?

**Pull request closed without merging**
