### PR TITLE
Fix include util functions

### PR DESCRIPTION
**Pull request by kobaska**
### Description
Fix include util functions to only include objects when key exists on the object

#### Related issues

- None

### Checklist
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ssh24** [comment]
@kobaska Could you please fix the commit message? The commit message needs follow the convention:
```
1. The first line of the commit message should not be longer than 50 characters long.
2. The second line should be empty.
3. Every consecutive line after should not be longer than 72 characters long.
```

**Comment by kobaska** [comment]
@ssh24 I have fixed the commit message

**Comment by ssh24** [comment]
@slnode test please

**Comment by jannyHou** [comment]
hi @kobaska I commented in your PR https://github.com/strongloop/loopback-datasource-juggler/pull/1465 and let's keep discussion here:

Sorry I don't find any issues open for this PR, and wondering do you fix it due to `kvMap.set()` fails when `id` is `null` or `undefined`?

Since when you assign `null` or `undefined` as property to an object, e.g.
```
var foo = {};
foo[null] = 1;
foo[undefined] = 2;
```

They are interpreted as string `'null'` and `'undefined'` and being added to `foo` instead of being ignored:
```
foo: {
  null: 1,
  undefined: 2
}
```

Could you elaborate more what's the context of your fix? Thanks!

**Comment by kjdelisle** [comment]
@jannyHou I think it's not about the keys themselves, but the values.

Working off your example, you could have something like this:
```
var item = {};
item[null] = null;
item[undefined] = undefined;

util.inspect(foo);
// returns '{ null: null, undefined: undefined }'
```

Since there's no particular worth to those items, they should probably be excluded.

**Comment by kobaska** [comment]
yes exactly what @kjdelisle mentions.

The specific use case we are using it for:

An Event could have 0 or many recommended options.

Example events:

- Treat paddock for lice event has 2 options:
1) Fertilise with Avenge product
2) Fertilise with Piranha product

So the fertilise event has optionId set to FERTILISE, which maps to Options model as a foreign key to give the two options.

- Move a mob event has no options to select from so option Id is set to null. 

In this case, the relation would fail for Move mob event, as the key is going to be null. Hence it should exclude that from the lookup.

model configs from loopback:

```
{
  "name": "ProgramEvent",
  "properties": {
     "optionGroup": {
        "type": "string"
    }
  },
  "relations": {
      "recommendationOptions": {
        "type": "hasMany",
        "model": "RecommendationOption",
        "foreignKey": "optionGroup",
        "primaryKey": "optionGroup"
    }
}

{
  "name": "RecommendationOption",
  "base": "RegionalTemplateBaseModel",
  "properties": {
    "orderIndex": {
      "type": "number"
    },
    "optionGroup": {
      "type": "string"
    }
  }
}

```

**Comment by kjdelisle** [comment]
@slnode test please

**Comment by kjdelisle** [comment]
@slnode test please
@kobaska Sorry for the wait, I'm going to run the tests again. You might need to rebase, but the PR still LGTM.

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by kobaska** [comment]
@kjdelisle I have done the rebase

**Comment by jannyHou** [comment]
@slnode test please

**Comment by kobaska** [comment]
@jannyHou @kjdelisle  Can we get this merged please?

**Comment by kjdelisle** [comment]
@slnode test please

**Comment by kjdelisle** [comment]
@kobaska If you're online around this time, then please rebase this and I'll run the tests again. If not, would you be able to give me access to your fork so I can rebase and land this?

**Comment by kjdelisle** [comment]
@kobaska It looks like there are some failing tests:

loopback-connector-postgresql downstream has 3 test failures and loopback-connector-oracle has 20 failures.

I've included a gist with the console output.
https://gist.github.com/kjdelisle/4b4de151541bb85b411a7d0c53b4186a

**Comment by kjdelisle** [comment]
@slnode test please

**Pull request closed without merging**
