### PR TITLE
Fixed nullCheck in validations for undefined attributes

### PR DESCRIPTION
**Pull request by billinghamj**
The current code `!(attr in this)` was not working (and I have written a unit test showing this). I have replaced it with a typeof undefined check. This then passes the unit test.

I have also written a couple of other unit tests to check other possible cases to ensure my change does not impact those.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by billinghamj** [comment]
Good point - I've made that change.

**Comment by billinghamj** [comment]
I can roll the commits together into one if you'd prefer

**Comment by raymondfeng** [comment]
@billinghamj +1 to squash the commits into one. Thanks!

**Comment by billinghamj** [comment]
👍

**Comment by billinghamj** [comment]
Thanks

**Pull request merged**
