### PR TITLE
Revert cass tests

### PR DESCRIPTION
**Pull request by Setogit**
### Description

Revert the changes for Cassandra to unblock downstream connector tests.
#### Related issues

- None

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by ssh24** [comment]
@Setogit Cassandra has 47 failures with the reverted code. Was that the behaviour before this change went in?

Cloudant downstream timed out. @slnode test please

**Comment by ssh24** [comment]
Cloudant is failing because of a delay in connecting to the docker image for cloudant hosted in a HDC machine. @jannyHou working on that to get the database container restarted.

**Comment by jannyHou** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by jannyHou** [comment]
The cloudant test start to fail due to timeout this week, I don't think it's related to this pr, so should not block our check it.

**Comment by ssh24** [comment]
PR to increase cloudant timeout: https://github.com/strongloop/loopback-connector-cloudant/pull/97

Unfortunately, mysql is also failing for timeout error. Very random indeed.

**Comment by loay** [comment]
probably 10000ms is a bit low. Maybe we need to increase it. The tests will probably pass with the next build in mysql

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Pull request closed without merging**
