### PR TITLE
Forward-port fix for "inverse polymorphic hasmany" from 2.x to master

### PR DESCRIPTION
**Pull request by oseme-techguy**
### Description

This PR provides a patch for the polymorphic hasMany Inverse relation for 3.x. The the fix was proposed and merged into 2.x with this PR #1080. This PR makes this fix available in 3.x.

#### Related issues
- Issue #1079

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by virkt25** [comment]
ok to test

**Comment by oseme-techguy** [comment]
@jannyHou, okay I will be glad to write patch fixes for them 😄

**Comment by virkt25** [comment]
@oseme-techguy Any updates on this?

**Comment by bajtos** [comment]
@oseme-techguy are you still keen to get this pull request landed? The code changes look good to me, now we need to fix tests to pass against our connectors too. Unfortunately, I don't see any obvious problem that would explain the failures.

**Pull request closed without merging**
