### PR TITLE
People want to use where on related models

### PR DESCRIPTION
**Pull request by f0rmiga**
### Description

People may want to get this to work:
`/customers/{customerId}/cars?filter={"where":{"model":{"neq":"sedan"}}}`

#### Related issues

- #1381 

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by dromaludaire** [comment]
This bug was introduced by #1381 
Imho, applying this fix is critical

**Comment by dromaludaire** [comment]
# How to reproduce

In an empty directory, install loopback-datasource-juggler and bluebird: `yarn add bluebird loopback-datasource-juggler`

The, execute the following program:

```javascript
global.Promise = require('bluebird');

let DataSource = require('loopback-datasource-juggler').DataSource,
    ds = new DataSource({connector: 'memory'});

let Physician = ds.createModel('Physician', {name: String}),
    Patient = ds.createModel('Patient', {name: String}),
    Appointment = ds.createModel('Appointment', {
        physicianId: Number,
        patientId: Number,
        appointmentDate: Date
    });

Appointment.belongsTo(Patient);
Appointment.belongsTo(Physician);
Physician.hasMany(Patient, {through: Appointment});
Patient.hasMany(Physician, {through: Appointment});


Physician.create({name: 'phy1'})
    .tap(ph => ph.patients.create({name: 'pat1'}))
    .then(ph => ph.patients({where: {name: 'pat1'}}))
    .then(patients => console.log('Patients matching where filter:', patients));
```

Expected output (shows up with loopback-datasource-juggler <= 3.6.1, or with the fix proposed by @f0rmiga ): 
> Patients matching where filter: [ { name: 'pat1', id: 1 } ]

Erroneous ouput (shows up with loopback-datasource-juggler >= 3.7.0 without the fix):
> Patients matching where filter: []

**Comment by jannyHou** [comment]
@f0rmiga Thank you for the contribution, your fix looks good to me, and could you add more test cases to catch the current failing scenario and verify your fix? 
In test file https://github.com/strongloop/loopback-datasource-juggler/blob/master/test/relations.test.js#L812

**Comment by f0rmiga** [comment]
Working on the test cases.

**Comment by jannyHou** [comment]
hi @f0rmiga any update on tests?

**Comment by joostdebruijn** [comment]
If I can help writing tests for this feature/bugfix, please let me know. I would be happy if this can land in a future release.

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by jannyHou** [comment]
@slnode test please

**Comment by f0rmiga** [comment]
Sorry for the delay

**Comment by jannyHou** [comment]
@f0rmiga Cool and no worries, could you rebase your code with master branch? Then I can trigger a test , if all downstream pass then we are good to land the PR, thanks!

**Comment by jannyHou** [comment]
And please also fix the **commit message** lint error, thanks!:
```
**************************************************
**
**  Linting commit logs
**
**  2 problems found:
**    48715ec - Fix TypeError: Cannot read property 'inq' of undefi: First line should be 50 characters or less (saw 84)
**    3fcb11a - Fix TypeError: Cannot read property 'inq' of undefi: First line should be 50 characters or less (saw 84)
**
```

I understand that juggler code changes very frequently and rebase in time is hard for contributors, if you don't mind you can follow guidelines in https://github.com/blog/2247-improving-collaboration-with-forks to give us the permission rebase code for you, don't worry you still get all credits :)

**Comment by f0rmiga** [comment]
@jannyHou You already got access to rebase. I could not fix the commit linter error. What should I do to fix that?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
