### PR TITLE
added hasMany relation discovery

### PR DESCRIPTION
**Pull request by jmls**
this PR adds the missing hasMany relationship discovery

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by raymondfeng** [comment]
@jmls Thank you for the patch. Can you please add a test case? It could in connectors.

**Comment by jmls** [comment]
I will add a test case asap

**Comment by raymondfeng** [comment]
@jmls Any update?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by jannyHou** [comment]
@jmls thank you for contribution, are you still keen to work on this feature? Could you rebase the code and add some test cases?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by jannyHou** [comment]
Thank you so much for contribution, unfortunately I am closing this PR since it's out of date, feel free to reopen it if there is any update, sorry for that.

**Comment by jmls** [comment]
I'll have another look given some spare time. Kinda gutted that the PR hangs around for over 2 years, but then it is closed just 8 days after asking me to rework it ...

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by jannyHou** [comment]
@jmls Glad to know that you are still interested, the PR hangs due to no update of test cases, I reopen it, take your time on the rework. Thanks.

**Pull request closed without merging**
