### PR TITLE
Allow nesting properties to be queried for memory connector

### PR DESCRIPTION
**Pull request by raymondfeng**
/to @bajtos or @ritch 

See https://github.com/strongloop/loopback/issues/517

### CODE REVIEW

**Comment by bajtos** [comment]
My main concern is about backwards compatibility. Is model-builder rejecting property names containing dots? If not, then we must distinguish between `nested.property` (referring to a property of a nested object) and `dot.name` (referring to a top-level property name containing a dot character).

**Comment by raymondfeng** [comment]
`slc loopback` checks property names.

**Comment by bajtos** [comment]
> `slc loopback` checks property names.

That's not sufficient, `slc loopback` is not the only way how to define models.

Here is an example that works for me now and most likely won't work with your patch:

```js
var Person = loopback.createModel('Person',
  {
    id: { type: 'string', id: true },
    'country.name': 'string'
  });

var app = loopback();
app.dataSource('db', {  connector: 'memory' });
app.model(Person, { dataSource: 'db' });

Person.create(
  { id: 'an-id', 'country.name': 'USA', 'custom.name': 'test' },
  function(err, created) {
    console.log('created', created);

    Person.find({ 'country.name': 'USA' }, function(err, found) {
      console.log('found', found);
    });
  });
```

And the output:

```
created { id: 'an-id', 'country.name': 'USA', 'custom.name': 'test' }
found [ { id: 'an-id', 'country.name': 'USA', 'custom.name': 'test' } ]
```

I am proposing to modify `getValue` to support both `nested.property` and `dot.name`:

```js
function getValue(obj, path) {
  if (obj == null) {
    return undefined;
  }

 var val = obj[path];
  if (val !== undefined) {
    return val;
  }

  val = obj;
  var keys = path.split('.');
  // etc.
}
```

Please add unit-tests to verify this new case.

Consider checking the connectors whether they support dot-names columns too. If they do, then we should add unit-tests to `test/datatype.test.js`, `test/basic-querying.test.js` and `test/manipulation.test.js` to verify that dot-named properties work everywhere as expected.

If you think dot-names properties should not be supported, then I am ok with that too, as long as we  modify model builder to throw an error when a property name contains any unsupported characters. (Report a deprecation warning in 2.x in order to preserve backwards compatibility.)

**Comment by raymondfeng** [comment]
To avoid confusions, the dot notation should be reserved for nesting properties. It should NOT be used as property names.

**Comment by bajtos** [comment]
> To avoid confusions, the dot notation should be reserved for nesting properties. It should NOT be used as property names.

I did a quick check of other connectors.

- MySQL tries to create a column with un-escaped dot in the name, which fails with `ER_WRONG_TABLE_NAME: Incorrect table name 'country'`

- MongoDB happily creates the record, however the `find` operation returns an empty list.

I suppose we can claim that property names containing a dot are invalid/unsupported usage and thus don't consider your patch as a breaking change, even though it can break existing application. @raymondfeng Is that what you are proposing?

In that case I am proposing to add a deprecation warning whenever user creates a property containing a dot in the name, so that people are at least notified about this issue. I can do it myself in a new pull request. Any objections?

**Comment by raymondfeng** [comment]
Instead of deprecation, I think we should report it as an error.

**Comment by bajtos** [comment]
@raymondfeng I added deprecation messages as a short-term solution per our discussion yesterday. PTAL and merge the patch if you are ok with the implementation.

**Comment by zane-insta** [comment]
@bajtos You mentioned that MongoDB returns an empty list with the find method. I am noticing this as well with v2.25.1. 
Is this expected to happen or is this patch supposed to make the find method work as well?
If this is expected do you know of a workaround that I can use in the short term to get the dot notation find working with MongoDB?

Specifically I am trying to filter location items based on whether or not they are within a rectangular boundary.

**Comment by bajtos** [comment]
@zane-insta My comment was referring to property names containing a dot, for example a "Place" model with two top-level properties called "location.lat" and "location.lng":

```json
{
  "location.lat": 10,
  "location.lng": 20
}
```

AFAIK, this patch is not changing the behaviour of the MongoDB connector.

Please open a new GH issue in https://github.com/strongloop/loopback-connector-mongodb and describe steps how we can reproduce the issue locally on our machines, ideally per our instructions for [Reporting issues](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report).

Possibly useful link: [How do I query a property with a dot in it](http://stackoverflow.com/questions/12878212/how-do-i-query-a-property-with-a-dot-in-it).

**Comment by zane-insta** [comment]
Hey @bajtos I actually found a much better way of getting the query I wanted. I just used the $geoWithin MongoDB query like so ...

```
var filter = {

...

  where: {
      location: {
         geoWithin: {
             $box: [
                 [<bottom left coordinates>],
                 [<top right coordinates>]
             ]
         }
      }
   }
}
```

I am not sure if you guys officially support the geoWithin query or not. 
If so would you like me to open an issue for documentation on the mongoDB connector?

**Comment by eugenehp** [comment]
hey @zane-insta have you moved further with the $geoWithin?

**Comment by zane-insta** [comment]
Hey @eugenehp I have just been using the filter I described above without any issues. I am still not sure if it is officially supported or not. I am planning on writing testcases for my code and dealing with it if/when they fail in the future.

**Pull request merged**
