### PR TITLE
WIP: Should not return error when property of type array is set to object …

### PR DESCRIPTION
**Pull request by mateuspontes**
Convert object to array on datajungler and not throw error with wrong type of data

### Description

If we create a model with object and we pass a object on a request, datajungler can't convert it and crashes the server.
The solution here is convert the object to array and return the keys.

#### Related issues

- #111

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by MaximeTroiano** [comment]
This is still an issue.

**Pull request closed without merging**
