### PR TITLE
fixed function linkOneToMany

### PR DESCRIPTION
**Pull request by kreddos**
### Description
Fixed 502 if relation object doesn't exist and query entity with remote-connector as datasource.

#### Related issues
Can be related to #951

### Checklist
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html).

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by 0candy** [comment]
Closing this PR as the fix is already in the code. See https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/include.js#L777

**Comment by somename85** [comment]
@0candy 
We still have this issue in our project.

I can't see fix in the code.

Code from your link
```
        function targetLinkingTask(next) {
            var targetObjsMap = targetObjMapByType[modelType];
            async.each(targets, linkOneToMany, next);
            function linkOneToMany(target, next) {
              var objList = targetObjsMap[target[relation.keyTo].toString()];
              async.each(objList, function(obj, next) {
                if (!obj) return next();
                obj.__cachedRelations[relationName] = target;
                processTargetObj(obj, next);
              }, next);
            }
          }
```

Code in PR:
```
        function targetLinkingTask(next) {
            var targetObjsMap = targetObjMapByType[modelType];
            async.each(targets, linkOneToMany, next);
            function linkOneToMany(target, next) {
              var objList = targetObjsMap[target[relation.keyTo].toString()];
              if (!objList) return next();
              async.each(objList, function(obj, next) {
                if (!obj) return next();
                obj.__cachedRelations[relationName] = target;
                processTargetObj(obj, next);
              }, next);
            }
          }
```

In PR was added string
`if (!objList) return next();`

**Comment by somename85** [comment]
If you have better solution for this fix i will appreciate any help.

**Comment by wj42ftns** [comment]
same problem

**Comment by 0candy** [comment]
@somename85 Ah, sorry, my mistake. Reopening this PR.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by 0candy** [comment]
@somename85 I would like to get this merged. But you haven't signed the cla yet. Also, the PR is against the wrong branch. It should either be 2.x or master. Would you still be interested in submitting a PR against the correct branch?

**Comment by somename85** [comment]
@0candy sorry for late answer, too much work now.
I hope I will be able to fix PR at the end of the week.

**Comment by ssh24** [comment]
Not sure who owns this PR. Could either @kreddos or @somename85 please rebase the PR, fix the commit linter messages and sign the CLA?

**Comment by somename85** [comment]
@0candy @ssh24 
You can close this PR. I cant communicate with kreddos now, so i have create new PR, https://github.com/strongloop/loopback-datasource-juggler/pull/1287 .

**Comment by ssh24** [comment]
Closing this as per #1287

**Pull request closed without merging**
