### PR TITLE
Fix include util functions

### PR DESCRIPTION
**Pull request by kobaska**
### Description
Backport PR#1463

#### Related issues
- connect to #1463

### Checklist
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by kobaska** [comment]
Yes, its the same as #1463. Fell free to close it

**Comment by jannyHou** [comment]
@kobaska cool thank you and I will figure out why some dependencies fail in the other PR.

**Pull request closed without merging**
