### PR TITLE
check if the value is an existance check, if it is then skip datatype…

### PR DESCRIPTION
**Pull request by tsanjoto**
… validation
#997

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by tsanjoto** [comment]
Any admins here can clarify what the Commit Linter is asserting? I can't check the details

**Comment by superkhau** [comment]
```
**************************************************
**
**  Linting commit logs
**
**  1 problems found:
**    8e841d5 - Skip Data Type Validation When Checking Existance O: First line should be 50 characters or less (saw 63)
**
**************************************************
```

**Comment by tsanjoto** [comment]
@superkhau sorry to bother you again. But it seems I can't get access on the details for PR Linter. I'm not sure if its just me who can't see the details.

Also I want to double check if the code logic is a good coding practice within your standards to solve #997

**Comment by superkhau** [comment]
@tsanjoto No problem, feel free to ping anytime. Did you run `npm run lint`? That should be good enough with dev rules at https://github.com/strongloop/loopback-contributor-docs/blob/master/style-guide.md.

**Comment by superkhau** [comment]
@slnode test please

**Comment by tsanjoto** [comment]
I did ran npm run lint, the eslint did not produce any error, But the PR Linter still fails.

as far as the rest of the other checks. I'm not sure how to fix those some of the failed checks. Are those errors really caused by the code?

how does this commit would cause an insufficient space in the system?

loopback-datasource-juggler/label=amazon-6
pm ERR! code ENOSPC
npm ERR! nospc This is most likely not a problem with npm itself
npm ERR! nospc and is related to insufficient space on your system.

**Comment by superkhau** [comment]
I see:

```
**  FAIL: allow-parameter-existance-check is behind master by 2 commits, rebase needed
```

Did you rebase your branch with master? Did you check if you're a few commits behind?

**Comment by Amir-61** [comment]
Hey @tsanjoto,

Thanks for the contribution. What is the status of this PR? Could you also please ad tests to verify the changes?

Thanks!

**Pull request closed without merging**
