### PR TITLE
Add last property to loaded event ctx

### PR DESCRIPTION
**Pull request by dotpack**
I want to calculate some properties of loaded records, after all records are loaded.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by Amir-61** [comment]
Hey @dotpack,

Thanks for the contribution!... Nitpick: I see you touched lots of unnecessary places, for example removed white spaces, lines..., could you please:

1) un-touch those lines that are not relevant to this PR
2) rebase your commit on top of master branch and trigger tests by `@slnode test please`.

Thanks!

**Comment by Amir-61** [comment]
@slnode test please

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
