### PR TITLE
Fix to avoid beaking filters for null fields

### PR DESCRIPTION
**Pull request by srova**
### Description
Fix to avoid breaking all "...where myfield is null " conditions, that have the following sintax in loopback:
{ where: { myfield: null } }

#### Related issues

- None

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ssh24** [comment]
@srova This PR could be related to https://github.com/strongloop/loopback-datasource-juggler/pull/1334

**Comment by ssh24** [comment]
Closing this. PR with the same fix landed https://github.com/strongloop/loopback-datasource-juggler/pull/1334

**Pull request closed without merging**
