### PR TITLE
Fix for #2582 : Nested queries with array object not working : memory…

### PR DESCRIPTION
**Pull request by pponugo**
Fix for strongloop/loopback#2582: Nested queries with array object not working : memory-connector

- Added logic to handle nested array objects
- Added unit test cases to support new logic
- Validated all existing unit test cases are passing.

Please accept pull request and let me know if there are any additional information I would need to provide.

The fix is for "version": "2.47.0",

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
@pponugo thank you for the pull request. The code changes look good to me. 

Please fix the commit message to follow our conventions, see [contributor docs](https://github.com/strongloop/loopback-contributor-docs/blob/master/git-commit-messages.md).

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by pponugo** [comment]
@bajtos, fixed the commit message but looks like some of the checks are failing. 
PR is showing out of date, even after merging **2.x** branch from 'strongloop/loopback-datasource-juggler' to 'pponugo/loopback-datasource-juggler', not sure what is the issue.

**Comment by bajtos** [comment]
> Merge branch '2.x' from strongloop to pponugo 		

@pponugo you should not merge the upstream branch into your feature branch, but rebase your feature branch on top of the upstream one.

You should run the following commands in your branch `2.x`:

```
$ git fetch strongloop/2.x
$ git rebase strongloop/2.x
$ git push -f
```

**Comment by bajtos** [comment]
@pponugo I have fixed the commit message for you and landed the patch via d385dfa9d. Thank you for the contribution!

**Pull request closed without merging**
