### PR TITLE
Set `removeAll` as an alias for `destroyAll`

### PR DESCRIPTION
**Pull request by Amir-61**
* Set `removeAll` as an alias for `destroyAll`
* It needs to be backported if the changes are right

/to: @superkhau 
/cc: @bajtos @raymondfeng

### CODE REVIEW

**Comment by superkhau** [comment]
@Amir-61 This change makes no sense to me. Why are you removing the original remove when one is instance based and the other is static. I am proposing we reject your changes unless you can explain why it is necessary

**Comment by Amir-61** [comment]
Hey @superkhau,

>@Amir-61 This change makes no sense to me. 

You may be right.

>Why are you removing the original remove when one is instance based and the other is static. I am proposing we reject your changes unless you can explain why it is necessary.

My intention of the changes: why did we have `remove` as an alias of `deleteAll` and `destroyAll`? Doesn't it make sense all use the same name convention (`destroy/delete/remove`+`All`)?

>It needs to be backported if the changes are right

On the second thought this is a breaking change; hence, we may not need to backport it (if the changes are accepted)

**Comment by superkhau** [comment]
>On the second thought this is a breaking change; hence, we may not need to backport it (if the changes are accepted)

That is my number one concern. I'm proposing you add a deprecation flag to the remove alias and dump it in juggler@4 to give anyone who is actually using the static remove enough time to change over to one of the other aliases. IMO though, we should just add `removeAll` like you propose *without* taking out remove for the best of both worlds (non-breaking and consistency). @bajtos @raymondfeng Thoughts?

>My intention of the changes: why did we have remove as an alias of deleteAll and destroyAll? Doesn't it make sense all use the same name convention (destroy/delete/remove+All)?

I actually believe we should have less aliases, but those other ones are already there. IMO, keeping just `delete` would be fine and probably cause less confusion/explaining.

**Comment by Amir-61** [comment]
>'m proposing you add a deprecation flag to the remove alias and dump it in juggler@4 to give anyone who is actually using the static remove enough time to change over to one of the other aliases.

Either your approach or we can deprecate it in `loopback-datasource-juggler@2.x` and this patch can be landed for our master branch which is `loopback-datasource-juggler@3.x`.

>I actually believe we should have less aliases

Thats why we are doing architectural redesign, which I'm spiking in this sprint.

**Comment by superkhau** [comment]
>Either your approach or we can deprecate it in loopback-datasource-juggler@2.x and this patch can be landed for our master branch which is loopback-datasource-juggler@3.x.

I'm fine with this solution too. I'm just not sure when 3x is going out lol. Either way as long as we show a deprecation message somewhere, I think you'll be good. ;)

>Thats why we are doing architectural redesign, which I'm spiking in this sprint.

Cool, jot that one in your notes. ;)

**Comment by bajtos** [comment]
> we should just add removeAll like you propose without taking out remove for the best of both worlds (non-breaking and consistency). @bajtos @raymondfeng Thoughts?

+1 for only adding the new alias without taking out any existing aliases.

> I'm just not sure when 3x is going out lol.

End of September. This means we should finish all breaking changes by the end of this sprint (2016-09-12).

**Comment by Amir-61** [comment]
Please lets get back to this PR after architectural design task of DAO.

Thanks!

**Pull request closed without merging**
