### PR TITLE
Fix test typo[2.x]

### PR DESCRIPTION
**Pull request by Amir-61**
Backporting
Connect to https://github.com/strongloop/loopback-datasource-juggler/pull/1016

CC: @supasate

### CODE REVIEW

**Comment by superkhau** [comment]
@Amir-61 Please use the full link in the commit body so that GitHub can convert it to a link automatically.

```
Backport loopback-datasource-juggler#1016
```

to

```
Backport https://github.com/strongloop/loopback-datasource-juggler/pull/1016
```

**Comment by Amir-61** [comment]
@superkhau  

I tried the full URL, but it is not gonna work; please note the commit linter fails; the commit description can be up to 72 char but `Backport https://github.com/strongloop/loopback-datasource-juggler/pull/1016` would be 76 chars.

**Comment by superkhau** [comment]
>I tried the full URL, but it is not gonna work; please note the commit linter fails; the commit description can be up to 72 char but Backport https://github.com/strongloop/loopback-datasource-juggler/pull/1016 would be 76 chars.

Interesting. @bajtos Do you have a solution to this? Should we relax the linter rules for URLs? It's nice to click on the commit message and have a link directly to the backport (and having the full link available in the command line when digging through history). I am also OK with @Amir-61's convention is also ok since it does convey the minimal amount of info to manually look for the PR in the GitHub UI, but the UX is not ideal.

**Comment by bajtos** [comment]
I am fine with using `#1016` as Node.js project does. GitHub is smart and will turn `#1016` into a clickable link #1016 when viewing the commit message on GitHub.com ([example](https://github.com/nodejs/node/commit/46633934fed7dfce289298cf16ea0f4161b77bb7)).

Note that it's important to use on of the following formats: `#123` or `user/repo#123`. `repo#123` is not recognized by GitHub AFAIK.

**Comment by superkhau** [comment]
>Note that it's important to use on of the following formats: #123 or user/repo#123. repo#123 is not recognized by GitHub AFAIK.

@Amir-61 Can you add this to the PR for backporting? Or submit a new on with updates because I think you merged in the other one already.

**Comment by Amir-61** [comment]
@superkhau Sent a PR: https://github.com/strongloop-internal/loopback-knowledge-base/pull/48 :-)

**Pull request merged**
