### PR TITLE
Create model foreign key matching type of opposite part of relation (even if it has a custom field type)

### PR DESCRIPTION
**Pull request by aol-nnov**
Initially this fix was proposed in strongloop/loopback-connector-postgresql#57 but @raymondfeng advised to move it into loopback-datasource-juggler.
So, here it is. :)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by aol-nnov** [comment]
@raymondfeng sorry for the delay - a bit busy here... I will add the testcase asap today or tomorrow.

**Comment by aol-nnov** [comment]
@raymondfeng here it is, finally ;)

**Comment by raymondfeng** [comment]
ok to test.

**Pull request merged**
