### PR TITLE
Add option for discoverModelDefinitions

### PR DESCRIPTION
**Pull request by jannyHou**
#### Related issues

https://github.com/strongloop-internal/scrum-apex/issues/127

- [x] Add option owner/schema
- [x] Fix typo

### CODE REVIEW

**Comment by dhmlau** [comment]
@jannyHou  CI failed because:
```
/home/jenkins/workspace/nb/loopback-datasource-juggler~master/526b6e0f/lib/datasource.js
  920:73  error  Trailing spaces not allowed  no-trailing-spaces
```

**Comment by loay** [comment]
@slnode test please

**Comment by rmg** [comment]
The commit message "Add option for discoverModelDefinitions" doesn't actually _add_ an option, it just documents an option. Would be better if the commit message was prefixed with `doc:` or some other indicator.

**Comment by dhmlau** [comment]
@strongloop/sq-lb-apex PTAL

**Comment by jannyHou** [comment]
LGTM. Thank you @dhmlau !

**Pull request merged**
