### PR TITLE
Async 'loaded' hook for find

### PR DESCRIPTION
**Pull request by PradnyaBaviskar**
Connect https://github.com/strongloop/loopback-datasource-juggler/issues/656#issuecomment-122942225

@raymondfeng, please review.
/cc @bajtos , @fabien

### CODE REVIEW

**Comment by raymondfeng** [comment]
There are a few issues in your previous `loaded` PR:

- We need to handle errors from the observers
  - https://github.com/PradnyaBaviskar/loopback-datasource-juggler/blob/issue656-findLoadedAsync/lib/dao.js#L295
  - https://github.com/PradnyaBaviskar/loopback-datasource-juggler/blob/issue656-findLoadedAsync/lib/dao.js#L502
  - https://github.com/PradnyaBaviskar/loopback-datasource-juggler/blob/issue656-findLoadedAsync/lib/dao.js#L627
  - https://github.com/PradnyaBaviskar/loopback-datasource-juggler/blob/issue656-findLoadedAsync/lib/dao.js#L1385
  - https://github.com/PradnyaBaviskar/loopback-datasource-juggler/blob/issue656-findLoadedAsync/lib/dao.js#L1417
  - https://github.com/PradnyaBaviskar/loopback-datasource-juggler/blob/issue656-findLoadedAsync/lib/dao.js#L1872
  - https://github.com/PradnyaBaviskar/loopback-datasource-juggler/blob/issue656-findLoadedAsync/lib/dao.js#L2370

- Why is https://github.com/PradnyaBaviskar/loopback-datasource-juggler/blob/issue656-findLoadedAsync/lib/dao.js#L1385 inside the `query && query.include` condition?

**Comment by PradnyaBaviskar** [comment]
> We need to handle errors from the observers

Done with the above fix.

**Comment by raymondfeng** [comment]
@PradnyaBaviskar I'm seeing test failures in the build. Can you run `npm test` to see?

**Comment by PradnyaBaviskar** [comment]
@raymondfeng, At my end, when I ran `npm test` it did NOT give me any test failure. Is this because I'm using Windows OS?

**Comment by raymondfeng** [comment]
ok to test

**Pull request merged**
