### PR TITLE
Fix composite id not working for embedsMany relations

### PR DESCRIPTION
**Pull request by ewrayjohnson**
Fixes strongloop/loopback#4282

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by dhmlau** [comment]
@ewrayjohnson, thanks for the PR.  Could you please add some tests to verify your changes? 
Also, could you please fix the commit linting error? 
```
**************************************************
**
**  Linting commit logs
**
**  2 problems found:
**    0b46d0a - Fixes bug: https://github.com/strongloop/loopback/i: First line should be 50 characters or less (saw 75)
**    759880a - Fixes:: Second line should be empty.<https://github.com/strongloop/loopback/issues/4282>
**
**************************************************
```

For details, here is our commit message guideline: https://loopback.io/doc/en/contrib/git-commit-messages.html. Thanks.

**Comment by ewrayjohnson** [comment]
I will add tests an fix linter errors very soon.

**Comment by ewrayjohnson** [comment]
I am still working on creating tests to show the bug and confirm the fix.

**Pull request closed without merging**
