### PR TITLE
Override collection name for arangodb connector

### PR DESCRIPTION
**Pull request by mrbatista**
### Description
Add collection name settings for arangodb database.
Required to pass common tests included in community connector

@ssh24 Backport of #1243

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ssh24** [comment]
@slnode ok to test

**Comment by ssh24** [comment]
@slnode ok to test

**Comment by ssh24** [comment]
@mrbatista Why is a backport required for this? 3.x is in our LTS plans and I do not believe backporting this is necessary.

**Comment by mrbatista** [comment]
@ssh24 The connector support only loopback 2.x.

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode ok to test

**Comment by ssh24** [comment]
@slnode test please

**Comment by rmg** [comment]
@ssh24 it seems this project now has enough downstream dependants that Jenkins is losing track of them mid-build :-(

@slnode test please

**Comment by ssh24** [comment]
@rmg What is the workaround for this?

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
Landing this PR. CI failure nothing related to the PR itself instead because there are too many 2.x downstream dependencies. Those repos/branches needs to be cleaned up from here https://cis-jenkins.swg-devops.com/job/npr/job/loopback-datasource-juggler~2.x/

**Pull request merged**
