### PR TITLE
fixes #753

### LINKED ISSUE #753: linkOneToMany objList is undefined.
I am getting the following error:

>TypeError: Cannot read property 'length' of undefined
>    at Object.async.each (/var/www/vhosts/greenback-api/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:152:17)
    at linkOneToMany (/var/www/vhosts/greenback-api/node_modules/loopback-datasource-juggler/lib/include.js:757:19)

The issue is coming from the following function:

        function targetLinkingTask(next) {
          async.each(targets, linkOneToMany, next);
          function linkOneToMany(target, next) {
            var targetId = target[relation.keyTo];
            var objList = objTargetIdMap[targetId.toString()];
            async.each(objList, function (obj, next) {
              if (!obj) return next();
              obj.__cachedRelations[relationName] = target;
              processTargetObj(obj, next);
            }, next);
          }
        }

For some reason objList is undefined. Is there a reason why this would happen and can you check if objList is undefined before attempting to iterate over it.

### PR DESCRIPTION
**Pull request by zmijevik**
fixes #753

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
@zmijevik thank you for the pull request. Please add a unit-test to verify your implementation and prevent regressions in the future.

**Comment by bajtos** [comment]
@raymondfeng I see you were already involved in a discussion about this issue, I'll defer code review to you.

**Comment by bajtos** [comment]
@zmijevik also please improve the commit message to describe what the change is fixing. The git commit history should be self-contained and not rely on GitHub issue tracker.

**Pull request merged**
