### PR TITLE
Override collection name for arangodb connector

### PR DESCRIPTION
**Pull request by mrbatista**
### Description
Add collection name settings for arangodb database.
Required to pass common tests included in community connector

#### Related issues

- imported tests fail on https://github.com/mrbatista/loopback-connector-arangodb/pull/44

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by mrbatista** [comment]
@bajtos @raymondfeng Is it possible to merge this PR? I have included some datasource tests in https://github.com/mrbatista/loopback-connector-arangodb connector.

Thanks.

**Comment by ssh24** [comment]
@slnode ok to test

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@mrbatista Thanks for the contribution. Your changes looks good to me. Could you please rebase your branch or give me the access to rebase your branch so we can proceed with the PR? Here is how to give your fork access: https://github.com/blog/2247-improving-collaboration-with-forks

**Comment by mrbatista** [comment]
@ssh24 rebased!

**Comment by ssh24** [comment]
@mrbatista Thank you! The PR has been landed :)

**Pull request merged**
