### PR TITLE
Update eslint

### PR DESCRIPTION
**Pull request by Amir-61**
* update eslint and fixing issues

As you suggested I skipped adding `use strict` for `/lib/dao.js`, `lib/relation-definition.js` and `lib/model.js` from eslint and added following line in `.eslintrc`:
```
    "strict": ["warn", "global"]
```

/to: @superkhau

### CODE REVIEW

**Comment by Amir-61** [comment]
@slnode test please

**Comment by Amir-61** [comment]
@slnode test please

**Comment by Amir-61** [comment]
@slnode test please

**Comment by Amir-61** [comment]
@slnode test please

**Comment by Amir-61** [comment]
@slnode test please

**Comment by Amir-61** [comment]
@slnode test please

**Comment by Amir-61** [comment]
@superkhau PTAL. Thanks :-)

**Comment by superkhau** [comment]
LGTM

**Comment by bajtos** [comment]
@Amir-61 @superkhau Guys, this change broke `npm test` in loopback. This can be seen from downstream CI builds too - see e.g. this [CIS build](https://cis-jenkins.swg-devops.com/job/ds/job/loopback~master/134):

```
Cannot assign to read only property 'type' of number
TypeError: Cannot assign to read only property 'type' of number
  at DataSource.defineForeignKey (node_modules/loopback-datasource-juggler/lib/datasource.js:1833:37)
  at Function.hasMany (node_modules/loopback-datasource-juggler/lib/relation-definition.js:638:24)
  at Function.hasMany (node_modules/loopback-datasource-juggler/lib/relations.js:74:29)
  at Context.defineProductAndCategoryModels (test/relations.integration.js:53:14)
```

Please be more careful in the future when landing changes while CI is not green.

**Comment by superkhau** [comment]
>Please be more careful in the future when landing changes while CI is not green.

@Amir-61 Please check CI before you land PRs with LGTM, I trust your decision as to whether you've checked or not.

**Pull request merged**
