### PR TITLE
Strip model properties before persisting [#754]

### PR DESCRIPTION
**Pull request by mrfelton**
Strip model properties before persisting on save() to prevent non-property data (eg relationships) from being persisted along with the model instance [#754]

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by superkhau** [comment]
Please sign the CLA. See https://cla.strongloop.com/agreements/strongloop/loopback-datasource-juggler

**Comment by mrfelton** [comment]
@superkhau I had already signed this agreement in the past. I have signed it again.

**Comment by bajtos** [comment]
This is a tricky change that may have subtle side effects. I am also worried about performance implications, since this is adding yet another initProperties+toObject roundtrip.
 
@raymondfeng what are your thoughts? I see that you have discussed this issue with @mrfelton in #754, I'll let you to review & land this patch.

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by superkhau** [comment]
@mrfelton Strange. I asked because the CLI said contributors didn't sign yet.

@rmg Do contributors need to sign for each repo individually each and every time?

**Comment by rmg** [comment]
@superkhau each repo is a separate CLA that has to be signed. Only StrongLoopers are auto-approved for all repos.

**Comment by superkhau** [comment]
@rmg TY.

@mrfelton That's why you have to sign again.

**Comment by mrfelton** [comment]
Got it. Makes sense. Thanks for the clarification @superkhau / @rmg

**Comment by superkhau** [comment]
@slnode test please

**Pull request closed without merging**
