### PR TITLE
Documentation for RelationDefinition.referencesMany

### PR DESCRIPTION
**Pull request by pastcompute**
### Description

This was not documented in any detail. I guess this should also be transcribed over to http://loopback.io/doc/en/lb3/Embedded-models-and-relations.html#referencesmany but I'm not sure where that gets generated from.

Done while looking at #1346

#### Related issues

- None

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by dhmlau** [comment]
@pastcompute , could you please resolve the conflicts in`lib/relation-definition.js` as indicated above?  thanks.

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
