### PR TITLE
resolve invalid date Type issue

### PR DESCRIPTION
**Pull request by ahmer-yasin**
I update DateType method for resolve the invalid date issue

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by ahmer-yasin** [comment]
Which checks were not succesfull please let me know

**Comment by superkhau** [comment]
Thanks for the contribution. Can you add some tests to prevent regressions in the future?

**Comment by ahmer-yasin** [comment]
Yes sure i love to do this

**Comment by superkhau** [comment]
Thanks. Just ping me and let me know when you have them ready and I'll get it reviewed/merged. ;)

**Comment by bajtos** [comment]
Closing as abandoned.

**Pull request closed without merging**
