### PR TITLE
Make tests work for other connectors as well as C*

### PR DESCRIPTION
**Pull request by Setogit**
### Description

Recreate PR to see how the downstream connectors build with the Cassandra support.
#### Related issues

- None

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by Setogit** [comment]
@slnode test please

**Comment by ssh24** [comment]
@Setogit This is the fix of your test case on master, if I am correct? Looks like CI is working on everything except postgresql. In that case we might not need the revert PR #1322 anymore.

**Comment by ssh24** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Pull request merged**
