### PR TITLE
Added nin filter to memory connector

### PR DESCRIPTION
**Pull request by ianbelcher**
The inq filter is included but the nin filter is missing.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by superkhau** [comment]
@ianbelcher Can you add a unit test to verify your change?

**Comment by ianbelcher** [comment]
Sorry @superkhau, been very busy. I'll try and get onto this in the next week or two.

**Comment by superkhau** [comment]
@ianbelcher NP, I feel exactly the same lol.

**Comment by rmg** [comment]
@slnode ok to test

**Comment by superkhau** [comment]
@slnode test please

**Comment by Multiply** [comment]
Please get this in as quick as possible. REALLY need this feature. :)

**Comment by superkhau** [comment]
>@ianbelcher Can you add a unit test to verify your change?

@ianbelcher ^

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by superkhau** [comment]
@Multiply Do you want to add the unit test to verify his changes?

**Comment by ianbelcher** [comment]
Sorry about this, I've been extremely busy for a few months now in a totally different framework. If @Multiply isn't able to get something happening as far as the tests (I guess they would pretty much mirror the inq filters tests) I'll try and free up some time in the next week or two to finally get this done!

**Comment by superkhau** [comment]
@ianbelcher Sure, no problem. Let's wait to see what @Multiply says.

**Comment by Multiply** [comment]
I don't mind writing a test for this, or https://github.com/strongloop/loopback-datasource-juggler/pull/624 for that matter, but if it is as you say @ianbelcher that it just need to be a mirror of the `inq` test, then I find it rather unclear.
The current tests I can see in master, is commented out (the `should allow In or NOT IN` test`). Am I missing other tests, where I could add the `nin` for?

**Comment by horiaradu** [comment]
@Multiply, these are the test cases I thought about.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by rmg** [comment]
@slnode ok to test

**Comment by superkhau** [comment]
Have you guys worked on the tests for this feature yet?

**Comment by Multiply** [comment]
@superkhau Already implemented here: https://github.com/strongloop/loopback-datasource-juggler/pull/860

**Comment by superkhau** [comment]
@Multiply Thanks for the update. I will close this as a duplicate.

**Pull request closed without merging**
