### PR TITLE
Strict Mode: Allow model to filter properties instead of throwing error

### PR DESCRIPTION
**Pull request by jsheely**
I want to be able to filter the out the properties given to a model from either inputs in remoting or outputs from juggler instead of throwing an error.

Small code code
```
if(strict !=='filter'){
   this.__unknownProperties.push(p);
}
```

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by jsheely** [comment]
I actually have no idea how to fix a commit linter issue that my commit message is over 50 characters by 8 characters. Do I have to scrap the entire pull request and do it again?

**Comment by ssh24** [comment]
@jsheely The way you did your rebase was not correct. Once I took over your branch, it had your incorrect changes. Could you open a clean PR and make sure your only change is 
```
        if (strict !== 'filter') {
          this.__unknownProperties.push(p);
        }
```
on `lib/model.js` file near line `251`. Please tag me to it so I can take a look. I will close this PR since it has a bunch of unneeded changes not related to the PR.

**Pull request closed without merging**
