### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by karanssj4**
drop v13 ad and add node v14

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-datasource-juggler) 👈

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](https://loopback.io/doc/en/contrib/style-guide-es6.html)
- [ ] Commit messages are following our [guidelines](https://loopback.io/doc/en/contrib/git-commit-messages.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@karanssj4, is it ok if I turn your PR to be a non-draft PR? Thanks. 
Seems like CI cannot complete if it's a draft PR.

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@karanssj4, thanks for your contribution. Your PR has landed! 🎉

**Pull request merged**
