### PR TITLE
Fix polymorphic hasMany inverse relation

### LINKED ISSUE #1079: Polymorphic hasMany inverse relation doesn't work on include filter
Using an include filter where the included relation is a polymorphic hasMany with invert set to true does not correctly take into account the invert option when figuring out which model to query, causing no records for the relation to return.

Given these model definitions:

``` js
Picture = db.define('Picture', { name: String });
Author = db.define('Author', { name: String });
PictureLink = db.define('PictureLink', {});

Author.hasMany(Picture, { through: PictureLink, polymorphic: 'imageable', invert: true });
Picture.hasMany(Author, { through: PictureLink, polymorphic: 'imageable' });
```

When running the below code snippet an empty array will always return for pictures, even if it actually contains valid entries:

``` js
Author.findOne({ include: 'pictures' }...); // this will not work, pictures will always be empty
```

However when querying the relation directly like this, things work fine:

``` js
// Given an author instance...
author.pictures(); // this will work, pictures will include all pictures
```

Here is the failing test case I wrote which shows this behaviour. Please correct me if I have misunderstood how the inverse relations should work:

``` js
  describe('polymorphic hasMany', function() {
    before(function(done) {
      Picture = db.define('Picture', { name: String });
      Author = db.define('Author', { name: String });
      PictureLink = db.define('PictureLink', {});

      Author.hasMany(Picture, { through: PictureLink, polymorphic: 'imageable', invert: true });
      Picture.hasMany(Author, { through: PictureLink, polymorphic: 'imageable' });

      db.automigrate(['Picture', 'Author', 'PictureLink'], done);
    });

    it('should properly query through an inverted relationship', function(done) {
      Author.create({ name: 'Steve' }, function(err, author) {
        author.pictures.create({ name: 'Steve pic 1' }, function(err, pic) {
          Author.findOne({ include: 'pictures' }, function(err, author) {
            if (err) { return done(err); }
            assert.equal(author.pictures().length, 1);
            assert.equal(author.pictures()[0].name, 'Steve pic 1');
            done();
          });
        });
      });
    });
  });
```

This issue might be related to #927, but I'm not sure.

### PR DESCRIPTION
**Pull request by jannyHou**
~Backport~ Check in pr https://github.com/strongloop/loopback-datasource-juggler/pull/1080 into correct branch 
I checked it in to 2.x-latest by accident.

cc @alexpit

### CODE REVIEW

**Comment by alexpls** [comment]
@jannyHou let me know if you need me to do anything to help this get merged in

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
Thank you @alexpls, there are lots of downstream dependency failing....I am investigating are they related to this pr or some existing bugs.

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
There are 14 failures on 2.x branch now...have to get pr https://github.com/strongloop/loopback-datasource-juggler/pull/1342 green then I will continue working on this one.

**Comment by loay** [comment]
The test case that seems to be failing was fixed in juggler 3.x with pr https://github.com/strongloop/loopback-datasource-juggler/pull/1265
If that fix gets backported, then it should fix the current failures as well or most of them at least

```
 basic-querying find supports non-empty inq:

      AssertionError: expected Array [ 1, 0 ] to equal Array [ 0, 1 ] (at '0', A has 1 and B has 0)
      + expected - actual

       [
      +  0
         1
      -  0
       ]
      
      at Assertion.fail (node_modules/should/lib/assertion.js:92:17)
      at Assertion.Object.defineProperty.value (node_modules/should/lib/assertion.js:164:19)
      at node_modules/loopback-datasource-juggler/test/basic-querying.test.js:470:29
```

**Comment by b-admike** [comment]
@slnode test please

**Comment by jannyHou** [comment]
The test is out-of-date, a trigger won't refresh it, we might need a new commit

**Comment by jannyHou** [comment]
FYI I made a mistake in the issue description, this is NOT a backport PR, originally I checked in the PR to a wrong branch 2.x-latest, and I am now merging it into the correct branch 2.x

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@slnode test please

**Comment by iamraphson** [comment]
@jannyHou @dhmlau please can we have this feature in 3.x or master?

**Pull request merged**
