### PR TITLE
Fix #1223 FindOrCreate missing error callback

### LINKED ISSUE #1223: FindOrCreate does not return errors on connector error
### Bug or feature request
- [x] Bug

### Description of feature (or steps to reproduce if bug)
There is a bug in dao.js that does not produce an error when it should on a connector issue. This yields issues for mongodb in particular. 

Reference as to fix:
https://github.com/strongloop/loopback-connector-mongodb/issues/296

Errors are overwritten by Model.notifyObserversOf should insert conditional and return just after findOrCreate callback (please :)

```
function _findOrCreate(query, data, currentInstance) {
    var modelName = self.modelName;
    function findOrCreateCallback(err, data, created) {
      console.log(!!err); //INSERT HERE: if (err) { return cb(err); }
      var context = {
        Model: Model,
        data: data,
        isNewInstance: created,
        hookState: hookState,
        options: options,
      };
      Model.notifyObserversOf('loaded', context, function(err) {
        if (err) return cb(err);

        var obj, Model = self.lookupModel(data);
```

### Additional information (Node.js version, LoopBack version, etc)
This Error is present in:
- 2.53.0 (one I'm using)
But also in your 3.0.0

### PR DESCRIPTION
**Pull request by jamesjjk**
### Description
Added error callback to findOrCreateCallback function

#### Related issues
https://github.com/strongloop/loopback-datasource-juggler/issues/1223

### Checklist

- [X] New tests added or existing tests modified to cover all changes
- [X] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by superkhau** [comment]
@jamesjjk Can you sign the CLA too?

**Comment by loay** [comment]
Hi @jamesjjk 
Can you please sign the CLA and make the change that was requested previously?
Thanks.

**Comment by ssh24** [comment]
@jamesjjk Could you please rebase your branch?

**Comment by dhmlau** [comment]
@slnode  test please

**Comment by rmg** [comment]
Done in e9baea77e028b63fce2d0ce3ee405a5eebf8132e.

**Pull request closed without merging**
