### PR TITLE
Let database generated id's not be required

### PR DESCRIPTION
**Pull request by devotis**
#899

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by superkhau** [comment]
Can you add some tests to verify your changes and prevent regressions in the future?

**Comment by devotis** [comment]
I've looked at `test/discovery.test.js`. To be honest I have no idea where to start. Where do I mock the tabels and definitions? I don't see where al the other properties of model properties like `dataPrecision`, `dataLength`, etc are tested. Those  are adjacent to `generated` so I would expect to find tests for those too. Where are `dataPrecision`, `dataLength`, etc tested?

**Comment by devotis** [comment]
@superkhau None of the tables to test on (customer, inventory, location, product, reservation and session) have an auto_numbered aka identity field. I can create another table. Can you help me with where I should add the model definition or create table statement for a new table for my tests?

**Comment by loay** [comment]
@devotis 
You can start by working on the actual tests that failing giving the "generated" property to be `undefined`. Thanks.

**Comment by devotis** [comment]
@loay I asked @superkhau about help with where I should add the model definition or create table statement for a new table for my tests.

**Comment by superkhau** [comment]
@devotis @loay can give you a hand here as he is taking over this functional area. That said, feel free to create your own tables using numbered/auto-identity field. However, depending on the type of back end you're using, you'll need to update the connectors along with the Juggler.

Let's keep it simple for now, you can test/simulate the behaviour using the in-memory connector. @loay, you can take it from here.

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@devotis Thank you for the contribution! 

I have rebased the branch for you and unfortunately there are some tests failing on Juggler. Could you start by looking into why those tests are failing?

**Comment by ssh24** [comment]
@slnode test please

**Pull request closed without merging**
