### PR TITLE
package: use loopback-connector@^4.0.0

### PR DESCRIPTION
**Pull request by kjdelisle**
#### Related issues
https://github.com/strongloop-internal/scrum-apex/issues/170
- None

### Checklist
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by Setogit** [comment]
LGTM

**Comment by kjdelisle** [comment]
@slnode test please

**Comment by ssh24** [comment]
MySQL tests timed out. It shouldn't be failing on CI. See: https://github.com/strongloop/loopback-datasource-juggler/pull/1312

@slnode test please

**Comment by kjdelisle** [comment]
Was confirming that the postgresql failures are unrelated. Seems to be caused by tests not properly releasing their connections back into the pool. Force-merging.

**Pull request merged**
