### PR TITLE
Missing the option argument issue #1388

### PR DESCRIPTION
**Pull request by dmellonch**
### Description
In scope.js, missing the option argument in find.relatedmodel
#### Related issues

#1388

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by dmellonch** [comment]
.ok\W+to\W+test.

**Comment by dhmlau** [comment]
@dmellonch , the Commit Linter check failed because the commit message is too long. 
```
**************************************************
**
**  Linting commit logs
**
**  1 problems found:
**    d997df8 - add option argument in relatedModel.find (reformat : First line should be 50 characters or less (saw 56)
**
**************************************************
```

**Comment by dhmlau** [comment]
Also, could you please add a test case to verify that it's doing what it's supposed to do?  Thanks!

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by dhmlau** [comment]
@dmellonch , could you please make the commit message less than 50 characters? thanks. 
Please see details in: 
https://github.com/strongloop/loopback-datasource-juggler/pull/1394#issuecomment-309187169

**Comment by dmellonch** [comment]
@dhmlau I make it now; all correct? thanks

**Comment by dhmlau** [comment]
@slnode  test please

**Comment by dhmlau** [comment]
@dmellonch , if you need help, you could give me access to your fork by clicking `Allow maintainers to edit` on the bottom right of the page.

**Comment by dmellonch** [comment]
@dhmlau, thanks for your help. I check "Allow edits from maintainers".

**Comment by dhmlau** [comment]
@dmellonch  thanks for fixing it up.  We realized that there's possibly something wrong happened from the previous rebase.  So I've created a separate PR: https://github.com/strongloop/loopback-datasource-juggler/pull/1417  to capture all your changes.  

Closing this PR.  Thanks for your contribution again.

**Comment by dmellonch** [comment]
@dhmlau thanks for your help. 
I'm sorry I have not been able to bring it down.

**Comment by ssh24** [comment]
@dhmlau I see https://github.com/strongloop/loopback-datasource-juggler/pull/1417 was created as a clean state for this PR but it is failing because the tests added are broken.

@dmellonch There are many downstream connectors failing with your test cases. Could you submit a new PR to fix those along with the current change? You could for example git clone the [mysql connector](https://github.com/strongloop/loopback-connector-mysql) and [setup a docker instance](https://github.com/strongloop/loopback-connector-mysql#running-tests) to run the test. Please make sure to `npm link` your branch in juggler to the mysql repo. Feel free to use any connector of your choice as well.

Also please ping me or any of the admins if you have problems with rebasing the code. We are more than happy to help!

@dhmlau I am going to be closing https://github.com/strongloop/loopback-datasource-juggler/pull/1417. We will land the final PR from @dmellonch with the fixes in.

**Pull request closed without merging**
