### PR TITLE
Refactor TTL test suite

### PR DESCRIPTION
**Pull request by superkhau**
Simplify TTL tests.

### CODE REVIEW

**Comment by superkhau** [comment]
@slnode test please

**Comment by superkhau** [comment]
@bajtos Unrelated failures, gonna merge this to get CI to pass for juggler.

**Comment by superkhau** [comment]
This is a prerequisite for #1074 to pass.

**Comment by bajtos** [comment]
@superkhau TBH, I have no idea what changes you made here and why they were necessary. It looks like you re-ordered tests (was that necessary? why?), and after that the diff is not able to tell whether you made some extra changes or not.

Could you please provide more details for the poor developers who will be scratching their heads in few months/years time trying to understand what happened here?

**Comment by bajtos** [comment]
@superkhau also do we need to forward-port this to `master`?

**Comment by superkhau** [comment]
>Could you please provide more details for the poor developers who will be scratching their heads in few months/years time trying to understand what happened here?

You are right, I should be writing a clearer message for these changes (and reducing each commit to single changes -- TBH, I just wanted to fix the failing tests on CI and move forward). So here goes:

- Tests messages were reworded and reorganized to make the scope of each test clearer
- Some of the code refactoring was done to make CI pass (the original tests were failing due to some expiry issue)
- Yes this needs to be forwardported to master (was too busy to do it on Friday, will be done by the time you read this)

**Pull request merged**
