### PR TITLE
Fix polymorphic hasMany inverse relation

### PR DESCRIPTION
**Pull request by iamraphson**
Description
This is just a fix for polymorphic hasMany Inverse relation for 3.x or master. PR was raised for this fix but It was merged into 2.x using this PR #1296 but it should be available in 3.x or master

Related issues
The issue was raised here #1079

cc @nitro404

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by virkt25** [comment]
@slnode ok to test

**Comment by nitro404** [comment]
Hmm, it looks like you have some indentation and spacing issues according to the build results. Try using `npm run lint` locally and resolving any warnings, then **amend** your existing commit with the changes. Thanks!

**Comment by iamraphson** [comment]
@nitro404 fixed indentation and spacing issues.

**Comment by nitro404** [comment]
Thank you for fixing! Not sure why the pull request builder is failing, someone else might have to weigh in here. If you could possibly fix your branch to only have one commit and undo your accidentally committed yarn lock file, it would be much appreciated. You can do this with SourceTree by resetting your branch to your original commit, then amending it with your changes and force pushing to replace your existing branch.

**Comment by nitro404** [comment]
@iamraphson Can you please squash your commits together? Thank you!

**Comment by iamraphson** [comment]
@nitro404 I think send a new PR for this. from the latest master branch.

**Comment by iamraphson** [comment]
@nitro404 This is the new PR https://github.com/strongloop/loopback-datasource-juggler/pull/1621. Can we move the converation there please?

**Pull request closed without merging**
