### PR TITLE
Test juggler@2.x dependencies

### PR DESCRIPTION
**Pull request by jannyHou**
Test 2.x dependency
There are 14 failures, could not backport any PR before getting them pass.

### CODE REVIEW

**Comment by jannyHou** [comment]
- [ ] gateway-director-management-interface@master
  Should not be tested, the valid branch is only `develop`

- [ ] loopback-connector-cassandra: 
  Does it support juggler@2.x? Since it's built with juggler@3.x from the begging.

**Comment by rmg** [comment]
This list is a mash up of `master` and `2.x` downstream builds because this PR has re-used the commit from #1340, which was an invalid PR against `master`. The build results were attached to 26375cf from that PR and thus are inherited by this PR.

Rebasing, amending, or simply adding on to this branch will clear the old/invalid build statuses and give a more accurate picture of what is actually a downstream build.

**Comment by jannyHou** [comment]
@rmg Thank you for jumping in, I am not aware of the closed PR still affects this one. Made a new commit and rebased.

**Comment by dhmlau** [comment]
@slnode test please

**Comment by jannyHou** [comment]
Fails due to code:
- [ ] cloudant@1.x
- [ ] informix@1.x
- [ ] mqlight@1.x
- [ ] mssql@2.x
- [ ] oracle@2.x
- [ ] postgresql@2.x

Fails on loopback-2.x:
- [ ] cloudant
- [ ] dashdb
- [ ] db2
- [ ] db2z
- [ ] mqlight
- [ ] mysql
- [ ] oracle

**Comment by dhmlau** [comment]
Discussion on the need to support `loopback-2.x` branch
https://github.com/strongloop/loopback-datasource-juggler/issues/1347

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode  test please

**Comment by dhmlau** [comment]
@slnode  test please

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode  test please

**Comment by rmg** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode  test please

There is `Segmentation fault` in db2@loopback-2.x. Kick off the test again.

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode  test please

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode  test please

**Comment by dhmlau** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@dhmlau Maybe you can take a look of https://github.com/strongloop/loopback-datasource-juggler/pull/1342#issuecomment-296331462

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@dhmlau Some downstreams are still failing. :(

**Comment by ssh24** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@ssh24, when i was last working on that, we have 3 issues left:
- dashdb - some deadlock issue in tests, so using docker image for tests might be the solution
- oracle - @0candy  @rmg  haven't got into a probable solution yet (from my understanding)
- swagger - intermittent problem because we're relying on http://petstore.swagger.io/v2/swagger.json, where its REST services are not always available

**Comment by dhmlau** [comment]
@slnode  test please

**Comment by dhmlau** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode  test please

**Comment by dhmlau** [comment]
From the latest run, we're down to 4
- [ ] loopback-connector-dashdb@loopback-2.x
- [ ] loopback-connector-oracle@2.x
- [ ] loopback-connector-oracle@loopback-2.x
- [ ] strong-agent@master

**Comment by dhmlau** [comment]
@slnode  test please
`strong-agent` has one test case failed due to timeout

**Comment by nVitius** [comment]
This has been open for well over a month now. Is there anything we can do to move this along? Where are discussions regarding these issues taking place?

**Comment by dhmlau** [comment]
@nVitius , thanks for your offer.  We have a handle of this except for the `loopback-connector-oracle`.  There is a PR https://github.com/strongloop/loopback-connector-oracle/pull/128 for the oracle connector.  @rmg and @0candy  might have better idea on that one.

**Comment by rmg** [comment]
@nVitius we're just using this PR to trigger automation so we can see what still needs work.

As I'm writing this we're at "**6 failing and 91 successful checks**". That used to be closer to "50 failing and 10 successful checks", so we're actually making pretty good progress I think.

The `strong-agent@master` and `health-check@develop` checks should be going green in the next test round or so.

**Comment by dhmlau** [comment]
@slnode  test please

**Comment by dhmlau** [comment]
@slnode test please

**Comment by jannyHou** [comment]
Closed https://github.com/strongloop/loopback-datasource-juggler/pull/1391, let's drop support for node7 in this PR.

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

Oracle was the last piece of the jigsaw. It was [fixed](https://github.com/strongloop/loopback-connector-oracle/pull/138) recently.

**Comment by ssh24** [comment]
Closing this PR. All juggler@2.x downstreams are green now!

**Pull request closed without merging**
