### PR TITLE
Move initialization of partitionBy option one level up from includeHasMany()

### PR DESCRIPTION
**Pull request by eugene-frb**

### CODE REVIEW

**Comment by Amir-61** [comment]
@eugene-frb Could you please clarify what you are trying to fix? Is there any test which fails with our implementation that will be passed by your change?
Please solve the merge conflict as well.

Thanks!

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
Closing as abandoned.

**Pull request closed without merging**
