### PR TITLE
fix avoid duplicate record on scope with promise

### PR DESCRIPTION
**Pull request by alexpit**
@bajtos

### CODE REVIEW

**Comment by Amir-61** [comment]
@slnode test please

**Comment by alexpit** [comment]
@slnode test please

**Comment by bajtos** [comment]
Nice, thank you for the contribution!

**Comment by alexpit** [comment]
@bajtos are the CI failures ("37 of 51 checks passed") expected somehow ?

**Comment by bajtos** [comment]
> are the CI failures ("37 of 51 checks passed") expected somehow ?

I am afraid our CI builds are still not very stable and tend to report intermittent failures :( If look at failed checks, they are all in dependent repositories. Since your change touched only test code, I find it extremely unlikely that it could break tests in dependent repositories and thus ignored those failed CI builds.

**Pull request merged**
