### PR TITLE
[WIP] feature: 404 error for findById() if resource is not found

### PR DESCRIPTION
**Pull request by hacksparrow**
404 error for findById() if resource is not found

#### Related issues

- connect to https://github.com/strongloop/loopback-datasource-juggler/issues/1619

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by bajtos** [comment]
I am against this change for two reasons:

- Juggler as the data-access layer should not be coupled with the specific requirements of transport layers like REST.
- In LoopBack 1.x-3.x, we are able to convert `null` result to `404` error. I am sure we can do that in LB4 too.

**Comment by virkt25** [comment]
> Juggler as the data-access layer should not be coupled with the specific requirements of transport layers like REST.

+1 **BUT** I don't think it should be returning null either. Should be a `count` of the deleted object or something other than null to indicate it didn't find anything to delete. Thoughts?

**Comment by bajtos** [comment]
> +1 BUT I don't think it should be returning null either. Should be a count of the deleted object or something other than null to indicate it didn't find anything to delete. Thoughts?

This is `findById` method. It returns either the model instance with the given `id`, or `null` when no such model instance was found.

I agree returning a `null` is not a great user experience, I think that's one of the reasons why `findById` in LB4 throws an error instead.

**Comment by bajtos** [comment]
We decided to pursue a different approach in LB4, this pull request is no longer needed.

**Comment by bajtos** [comment]
We decided to pursue a different approach in LB4, this pull request is no longer needed.

**Pull request closed without merging**
