### PR TITLE
Fixed typo & added the filter units

### PR DESCRIPTION
**Pull request by thefinnomenon**
Fixed typo in nearby sort function & added the ability to specify units when filtering for nearby points.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by raymondfeng** [comment]
ok to test

**Comment by raymondfeng** [comment]
@thefinnomenon The build is failing - 
```
/mnt/jenkins/workspace/loopback-datasource-juggler.pr/89d66e82/lib/geo.js:55
    var d = GeoPoint.distanceBetween(origin, loc, {type: unit}));
                                                               ^
SyntaxError: Unexpected token )
```

Can you fix it?

**Comment by thefinnomenon** [comment]
Fixed. Do I need to do a new pull request?

**Comment by raymondfeng** [comment]
No, as long as you commit into the same branch.

**Comment by raymondfeng** [comment]
ok to test

**Pull request merged**
