### PR TITLE
Make sure id properties cannot be changed

### PR DESCRIPTION
**Pull request by raymondfeng**
/to @ritch or @bajtos 
/cc @fabien 

This PR prevents id values to be changed during prototype.attributes.

### CODE REVIEW

**Comment by bajtos** [comment]
LGTM.

**Comment by bajtos** [comment]
I am wondering if this is a breaking change?

**Comment by raymondfeng** [comment]
This is to cover a hole that could violates the data integrity. If an existing app `use` this `feature` by accident, we should break it to get the security issue exposed sooner than later.

**Comment by nicholasareed** [comment]
@raymondfeng this breaks for mongodb users (or for any databases who have an ObjectId for the id). Perhaps a warning should popup (instead of an Error) and 

    delete data[idName];

or modify the if statement to be 

    if (data[idName] !== undefined && data[idName] !== inst[idName] && data[idName].toString() !== inst[idName].toString()) {

**Comment by raymondfeng** [comment]
This should have been fixed by https://github.com/strongloop/loopback-datasource-juggler/pull/522.

**Comment by nicholasareed** [comment]
Appears that it was, sorry I missed the connection! Where can I find the process for how it gets moved to npm? The install there is the broken version.

**Pull request merged**
