### PR TITLE
fix beforeDestroy and afterDestroy hooks not trigered if called with destroyById

### PR DESCRIPTION
**Pull request by kevinsproles**
fixes:
https://github.com/strongloop/loopback-datasource-juggler/issues/202
https://github.com/strongloop/loopback-datasource-juggler/issues/142

Thanks to @jcsmesquita

### CODE REVIEW

**Comment by jannyHou** [comment]
@kevinsproles Could you sign the CLA and rebase your code & add some test cases to verify your change? Thanks.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by jannyHou** [comment]
@kevinsproles thank you so much for contribution while I think it's already fixed according to https://github.com/strongloop/loopback-datasource-juggler/issues/202#issuecomment-72641965
and https://github.com/strongloop/loopback-datasource-juggler/issues/142#issuecomment-72642028

And I don't see any new issues open which refers to those old bugs so I assume loopback doesn't run into that bug any more.
Closing the pr now. 

Feel free to REOPEN it if you have further questions or anything else we can help. Thanks for understanding.

**Pull request closed without merging**
