### PR TITLE
Fix for https://github.com/strongloop/loopback-datasource-juggler/issues/571

### PR DESCRIPTION
**Pull request by ningsuhen**
HasManyThrough is inconsistent because of arbitrary order of foreign keys returned by findBelongsTo. This fix sorts the result so that the first key is the one that is mapped to the base (modelFrom) model.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by raymondfeng** [comment]
@ningsuhen Thank you for the patch. Can you add a test case?

**Comment by ningsuhen** [comment]
Thanks @raymondfeng , Test case has been added.

**Comment by raymondfeng** [comment]
ok to test

**Pull request merged**
