### PR TITLE
handle deep geo-near queries

### PR DESCRIPTION
**Pull request by ebarault**
PR #1216 was reverted: CIS-Jenkins was down when that PR was merged hence failures regarding other connector were not captured.

This is the follow-up PR to address failures with connectors.

connected to https://github.com/strongloop-internal/scrum-apex/issues/168

### CODE REVIEW

**Comment by ssh24** [comment]
Latest status:
- MongoDB is failing because of https://github.com/strongloop/loopback-connector-mongodb/pull/322. Need to land this first in-order to land that. All tests pass locally when npm linked and ran for mongodb.
- Postgresql is failing because of other test cases being broken. https://github.com/strongloop-internal/scrum-apex/issues/167
- DashDB is failing because of `POINT` type not being supported? Need to do further investigation on that.

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
PR is ready to land. @ebarault Thank you for the contribution! Took a long time too land it but your patience was worthy. :)

**Comment by ebarault** [comment]
@ssh24 thanks for running that through!

**Pull request merged**
