### PR TITLE
objListis empty in linkOneToMany function

### PR DESCRIPTION
**Pull request by somename85**
### Description
Fixed 502 if relation object doesn't exist and query entity with remote-connector as datasource.

#### Related issues
Can be related to
- #951

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ssh24** [comment]
@somename85 Could you please add some unit tests to prevent future regressions on this patch?

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@somename85 Thank you for the contribution. PR is ready to be landed.

**Comment by gmenih341** [comment]
Any idea when this is going to be released?

**Comment by kartsims** [comment]
Same problem here, still relying on `2.x`...

Temporarily fixed by changing the dependency to this branch in my `package.json` : 

```
    "loopback-datasource-juggler": "git://github.com/strongloop/loopback-datasource-juggler#2.x",
```

Not really happy with that, could someone let us know when a new release is out ?

**Pull request merged**
