### PR TITLE
fix incorrect where clause for polymorphic through

### PR DESCRIPTION
**Pull request by beaglez**
Fix for https://github.com/strongloop/loopback-datasource-juggler/issues/927

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by Amir-61** [comment]
@slnode test please

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
